# Internal Dependencies
<br>  

### References
- [Analyze java package metrics in a graph database](https://joht.github.io/johtizen/data/2023/04/21/java-package-metrics-analysis.html)
- [Calculate metrics](https://101.jqassistant.org/calculate-metrics/index.html)
- [Neo4j Python Driver](https://neo4j.com/docs/api/python-driver/current)

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plot
from neo4j import GraphDatabase

In [2]:
# Please set the environment variable "NEO4J_INITIAL_PASSWORD" in your shell 
# before starting jupyter notebook to provide the password for the user "neo4j". 
# It is not recommended to hardcode the password into jupyter notebook for security reasons.

driver = GraphDatabase.driver(uri="bolt://localhost:7687", auth=("neo4j", os.environ.get("NEO4J_INITIAL_PASSWORD")))
driver.verify_connectivity()

In [3]:
def get_cypher_query_from_file(cypher_file_name : str):
    with open(cypher_file_name) as file:
        return ' '.join(file.readlines())


def query_cypher_to_data_frame(filename : str, limit: int = -1):
    """
    Execute the Cypher query of the given file and returns the result.
    filename : str : The name of the file containing the Cypher query
    limit : int : The optional limit of rows to optimize the query. Default = -1 = no limit
    """
    cypher_query = get_cypher_query_from_file(filename)
    if limit > 0:
        cypher_query = "{query}\nLIMIT {row_limit}".format(query = cypher_query, row_limit = limit)
    records, summary, keys = driver.execute_query(cypher_query)
    return pd.DataFrame([r.values() for r in records], columns=keys)


def query_first_non_empty_cypher_to_data_frame(*filenames : str, limit: int = -1):
    """
    Executes the Cypher queries of the given files and returns the first result that is not empty.
    If all given file names result in empty results, the last (empty) result will be returned.
    By additionally specifying "limit=" the "LIMIT" keyword will appended to query so that only the first results get returned.
    """    
    result=pd.DataFrame()
    for filename in filenames:
        result=query_cypher_to_data_frame(filename, limit)
        if not result.empty:
            return result
    return result

In [4]:
#The following cell uses the build-in %html "magic" to override the CSS style for tables to a much smaller size.
#This is especially needed for PDF export of tables with multiple columns.

In [5]:
%%html
<style>
/* CSS style for smaller dataframe tables. */
.dataframe th {
    font-size: 8px;
}
.dataframe td {
    font-size: 8px;
}
</style>

In [6]:
# Pandas DataFrame Display Configuration
pd.set_option('display.max_colwidth', 300)

## 1 - Modules

List the modules this notebook is based on. Different sorting variations help finding modules by their features and support larger code bases where the list of all modules gets very long.

Only the top 30 entries are shown. The whole table can be found in the following CSV report:  
`List_all_Typescript_modules`

In [7]:
internalModules = query_cypher_to_data_frame("../cypher/Internal_Dependencies/List_all_Typescript_modules.cypher")

Received notification from DBMS server: {severity: WARNING} {code: Neo.ClientNotification.Statement.UnknownPropertyKeyWarning} {category: UNRECOGNIZED} {title: The provided property key is not in the database} {description: One of the property names in your query is not available in the database, make sure you didn't misspell it or that the label is available when you run this statement in your application (the missing property name is: numberOfGitCommits)} {position: line: 9, column: 31, offset: 594} for query: '// List all existing internal Typescript modules. Requires "Set_localRootPath_for_modules.cypher", "Set_number_of...commits.cypher".\n \n MATCH (internalModule:TS:Module)-[:EXPORTS]->(internalElement:TS)\n  WITH internalModule.name                            AS moduleName\n      ,internalModule.rootProjectName                 AS rootProjectName\n      ,internalModule.localModuleDir                  AS localModuleDir\n      ,internalModule.incomingDependencies            AS incomingDependencies\n      ,internalModule.outgoingDependencies            AS outgoingDependencies\n      ,coalesce(internalModule.numberOfGitCommits, 0) AS numberOfGitCommits\n      ,COUNT(DISTINCT internalElement.globalFqn)      AS numberOfElements\n RETURN rootProjectName, moduleName, numberOfElements, numberOfGitCommits, incomingDependencies, outgoingDependencies'

### Table 1a - Top 30 modules with the highest element count

In [8]:
# Sort by number of modules descending
internalModules.sort_values(by=['numberOfElements','moduleName'], ascending=[False, True]).reset_index(drop=True).head(30)

,rootProjectName,moduleName,numberOfElements,numberOfGitCommits,incomingDependencies,outgoingDependencies
0,react-router-7.13.2,react-router,171,0,379,13
1,react-router-7.13.2,utils,86,0,175,3
2,react-router-7.13.2,react-router,40,0,112,4
3,react-router-7.13.2,router,34,0,53,1
4,react-router-7.13.2,utils,28,0,36,28
5,react-router-7.13.2,history,25,0,40,0
6,react-router-7.13.2,utils,24,0,46,0
7,react-router-7.13.2,server,22,0,40,17
8,react-router-7.13.2,routeModules,21,0,27,6
9,react-router-7.13.2,context,19,0,11,10
10,react-router-7.13.2,plugin,17,0,9,150
11,react-router-7.13.2,routes,15,0,25,28
12,react-router-7.13.2,dom,14,0,6,0
13,react-router-7.13.2,config,13,0,16,40
14,react-router-7.13.2,flatRoutes,13,0,1,15
15,react-router-7.13.2,route-chunks,12,0,8,310
16,react-router-7.13.2,sessions,11,0,3,10
17,react-router-7.13.2,instrumentation,9,0,14,0
18,react-router-7.13.2,links,8,0,0,9
19,react-router-7.13.2,routes,8,0,9,0
20,react-router-7.13.2,single-fetch,8,0,5,4
21,react-router-7.13.2,dom-export,7,0,19,0
22,react-router-7.13.2,react-router-node,7,0,2,0
23,react-router-7.13.2,route-data,7,0,6,0
24,react-router-7.13.2,cookies,6,0,19,4
25,react-router-7.13.2,fog-of-war,6,0,3,5
26,react-router-7.13.2,prerender,6,0,2,16
27,react-router-7.13.2,react-router-cloudflare,6,0,0,0
28,react-router-7.13.2,server,6,0,3,22
29,react-router-7.13.2,server,6,0,3,18

### Table 1b - Top 30 modules with the highest number of incoming dependencies

The following table lists the top 30 internal modules that are used the most by other modules (highest count of incoming dependencies, highest in-degree).

In [9]:
# Sort by number of incoming dependencies descending
internalModules.sort_values(by=['incomingDependencies','moduleName'], ascending=[False, True]).reset_index(drop=True).head(30)

,rootProjectName,moduleName,numberOfElements,numberOfGitCommits,incomingDependencies,outgoingDependencies
0,react-router-7.13.2,react-router,171,0,379,13
1,react-router-7.13.2,utils,86,0,175,3
2,react-router-7.13.2,react-router,40,0,112,4
3,react-router-7.13.2,router,34,0,53,1
4,react-router-7.13.2,utils,24,0,46,0
5,react-router-7.13.2,history,25,0,40,0
6,react-router-7.13.2,server,22,0,40,17
7,react-router-7.13.2,utils,28,0,36,28
8,react-router-7.13.2,routeModules,21,0,27,6
9,react-router-7.13.2,routes,15,0,25,28
10,react-router-7.13.2,cookies,6,0,19,4
11,react-router-7.13.2,dom-export,7,0,19,0
12,react-router-7.13.2,config,13,0,16,40
13,react-router-7.13.2,vite,2,0,15,5
14,react-router-7.13.2,instrumentation,9,0,14,0
15,react-router-7.13.2,entry,5,0,12,0
16,react-router-7.13.2,build,5,0,11,0
17,react-router-7.13.2,context,19,0,11,10
18,react-router-7.13.2,plugin,17,0,9,150
19,react-router-7.13.2,react-router,5,0,9,4
20,react-router-7.13.2,routes,8,0,9,0
21,react-router-7.13.2,babel,2,0,8,1
22,react-router-7.13.2,prompts-prompt-base,2,0,8,14
23,react-router-7.13.2,route-chunks,12,0,8,310
24,react-router-7.13.2,data,2,0,7,0
25,react-router-7.13.2,dom,14,0,6,0
26,react-router-7.13.2,links,3,0,6,0
27,react-router-7.13.2,route-data,7,0,6,0
28,react-router-7.13.2,routes,4,0,6,9
29,react-router-7.13.2,commands,5,0,5,15

### Table 1c - Top 30 modules with the highest number of outgoing dependencies

The following table lists the top 30 internal modules that are depending on the highest number of other modules (highest count of outgoing dependencies, highest out-degree).

In [10]:
# Sort by number of outgoing dependencies descending
internalModules.sort_values(by=['outgoingDependencies','moduleName'], ascending=[False, True]).reset_index(drop=True).head(30)

,rootProjectName,moduleName,numberOfElements,numberOfGitCommits,incomingDependencies,outgoingDependencies
0,react-router-7.13.2,route-chunks,12,0,8,310
1,react-router-7.13.2,plugin,17,0,9,150
2,react-router-7.13.2,plugin,1,0,1,54
3,react-router-7.13.2,config,13,0,16,40
4,react-router-7.13.2,copy-template,2,0,2,33
5,react-router-7.13.2,remove-exports,1,0,2,30
6,react-router-7.13.2,with-props,1,0,1,29
7,react-router-7.13.2,create-react-router,2,0,0,28
8,react-router-7.13.2,routes,15,0,25,28
9,react-router-7.13.2,utils,28,0,36,28
10,react-router-7.13.2,generate,5,0,5,24
11,react-router-7.13.2,server,6,0,3,22
12,react-router-7.13.2,styles,4,0,3,22
13,react-router-7.13.2,server,6,0,3,18
14,react-router-7.13.2,worker,5,0,5,18
15,react-router-7.13.2,server,22,0,40,17
16,react-router-7.13.2,prerender,6,0,2,16
17,react-router-7.13.2,cloudflare-dev-proxy,1,0,1,15
18,react-router-7.13.2,commands,5,0,5,15
19,react-router-7.13.2,flatRoutes,13,0,1,15
20,react-router-7.13.2,prompts-prompt-base,2,0,8,14
21,react-router-7.13.2,react-router,171,0,379,13
22,react-router-7.13.2,vite-node,2,0,2,13
23,react-router-7.13.2,loading-indicator,1,0,1,12
24,react-router-7.13.2,warn-on-client-source-maps,1,0,2,12
25,react-router-7.13.2,dev,2,0,1,11
26,react-router-7.13.2,stream,4,0,4,11
27,react-router-7.13.2,context,19,0,11,10
28,react-router-7.13.2,sessions,11,0,3,10
29,react-router-7.13.2,typegen,3,0,4,10

### Table 1d - Top 30 modules with the lowest element count

In [11]:
# Sort by number of elements ascending
internalModules.sort_values(by=['numberOfElements','moduleName'], ascending=[True, True]).reset_index(drop=True).head(30)

,rootProjectName,moduleName,numberOfElements,numberOfGitCommits,incomingDependencies,outgoingDependencies
0,react-router-7.13.2,actions,1,0,3,0
1,react-router-7.13.2,arcTableSessionStorage,1,0,1,6
2,react-router-7.13.2,binaryTypes,1,0,1,0
3,react-router-7.13.2,browser,1,0,1,0
4,react-router-7.13.2,cloudflare,1,0,0,0
5,react-router-7.13.2,cloudflare-dev-proxy,1,0,1,15
6,react-router-7.13.2,combine-urls,1,0,1,0
7,react-router-7.13.2,cookieStorage,1,0,2,2
8,react-router-7.13.2,data,1,0,0,0
9,react-router-7.13.2,detectPackageManager,1,0,1,1
10,react-router-7.13.2,entry,1,0,1,0
11,react-router-7.13.2,errors,1,0,1,0
12,react-router-7.13.2,flatten,1,0,1,0
13,react-router-7.13.2,has-dependency,1,0,2,1
14,react-router-7.13.2,has-rsc-plugin,1,0,2,3
15,react-router-7.13.2,href,1,0,2,0
16,react-router-7.13.2,invariant,1,0,0,0
17,react-router-7.13.2,invariant,1,0,0,0
18,react-router-7.13.2,invariant,1,0,0,0
19,react-router-7.13.2,is-react-router-repo,1,0,2,5
20,react-router-7.13.2,load-dotenv,1,0,2,4
21,react-router-7.13.2,loading-indicator,1,0,1,12
22,react-router-7.13.2,markup,1,0,1,0
23,react-router-7.13.2,memoryStorage,1,0,2,1
24,react-router-7.13.2,normalizeSlashes,1,0,1,3
25,react-router-7.13.2,normalizeSlashes,1,0,2,3
26,react-router-7.13.2,optimize-deps-entries,1,0,2,3
27,react-router-7.13.2,params,1,0,0,0
28,react-router-7.13.2,params,1,0,1,0
29,react-router-7.13.2,plugin,1,0,1,54

### Table 1e - Top 30 modules with the lowest number of incoming dependencies

The following table lists the top 30 internal modules that are used the least by other modules (lowest count of incoming dependencies, lowest in-degree).

In [12]:
# Sort by number of incoming dependencies ascending
internalModules.sort_values(by=['incomingDependencies','moduleName'], ascending=[True, True]).reset_index(drop=True).head(30)

,rootProjectName,moduleName,numberOfElements,numberOfGitCommits,incomingDependencies,outgoingDependencies
0,react-router-7.13.2,cloudflare,1,0,0,0
1,react-router-7.13.2,create-react-router,2,0,0,28
2,react-router-7.13.2,data,1,0,0,0
3,react-router-7.13.2,global,2,0,0,0
4,react-router-7.13.2,internal,2,0,0,0
5,react-router-7.13.2,invariant,1,0,0,0
6,react-router-7.13.2,invariant,1,0,0,0
7,react-router-7.13.2,invariant,1,0,0,0
8,react-router-7.13.2,links,8,0,0,9
9,react-router-7.13.2,params,1,0,0,0
10,react-router-7.13.2,react-router-cloudflare,6,0,0,0
11,react-router-7.13.2,react-router-fs-routes,1,0,0,5
12,react-router-7.13.2,react-router-remix-routes-option-adapter,1,0,0,0
13,react-router-7.13.2,route-modules,2,0,0,0
14,react-router-7.13.2,run,1,0,0,9
15,react-router-7.13.2,server,1,0,0,0
16,react-router-7.13.2,vite,2,0,0,0
17,react-router-7.13.2,arcTableSessionStorage,1,0,1,6
18,react-router-7.13.2,binaryTypes,1,0,1,0
19,react-router-7.13.2,browser,1,0,1,0
20,react-router-7.13.2,build,2,0,1,8
21,react-router-7.13.2,cloudflare-dev-proxy,1,0,1,15
22,react-router-7.13.2,combine-urls,1,0,1,0
23,react-router-7.13.2,detectPackageManager,1,0,1,1
24,react-router-7.13.2,dev,2,0,1,11
25,react-router-7.13.2,entry,1,0,1,0
26,react-router-7.13.2,errors,1,0,1,0
27,react-router-7.13.2,fileStorage,2,0,1,9
28,react-router-7.13.2,flatRoutes,13,0,1,15
29,react-router-7.13.2,flatten,1,0,1,0

### Table 1f - Top 30 modules with the lowest number of outgoing dependencies

The following table lists the top 30 internal modules that are depending on the lowest number of other modules (lowest count of outgoing dependencies, lowest out-degree).

In [13]:
# Sort by number of outgoing dependencies ascending
internalModules.sort_values(by=['outgoingDependencies','moduleName'], ascending=[True, True]).reset_index(drop=True).head(30)

,rootProjectName,moduleName,numberOfElements,numberOfGitCommits,incomingDependencies,outgoingDependencies
0,react-router-7.13.2,actions,1,0,3,0
1,react-router-7.13.2,binaryTypes,1,0,1,0
2,react-router-7.13.2,browser,1,0,1,0
3,react-router-7.13.2,build,5,0,11,0
4,react-router-7.13.2,cache,2,0,3,0
5,react-router-7.13.2,cloudflare,1,0,0,0
6,react-router-7.13.2,combine-urls,1,0,1,0
7,react-router-7.13.2,config,4,0,5,0
8,react-router-7.13.2,context,2,0,3,0
9,react-router-7.13.2,crypto,2,0,2,0
10,react-router-7.13.2,data,1,0,0,0
11,react-router-7.13.2,data,2,0,7,0
12,react-router-7.13.2,defineRoutes,3,0,2,0
13,react-router-7.13.2,dom,14,0,6,0
14,react-router-7.13.2,dom-export,7,0,19,0
15,react-router-7.13.2,entry,5,0,12,0
16,react-router-7.13.2,entry,1,0,1,0
17,react-router-7.13.2,errors,4,0,2,0
18,react-router-7.13.2,errors,1,0,1,0
19,react-router-7.13.2,errors,5,0,5,0
20,react-router-7.13.2,flatten,1,0,1,0
21,react-router-7.13.2,format,4,0,1,0
22,react-router-7.13.2,future,2,0,3,0
23,react-router-7.13.2,global,2,0,0,0
24,react-router-7.13.2,history,25,0,40,0
25,react-router-7.13.2,href,1,0,2,0
26,react-router-7.13.2,instrumentation,9,0,14,0
27,react-router-7.13.2,internal,2,0,0,0
28,react-router-7.13.2,invariant,1,0,0,0
29,react-router-7.13.2,invariant,1,0,0,0

## 2 - Cyclic Dependencies

Cyclic dependencies occur when one module uses an elements of another module and vice versa. 
These dependencies can lead to problems when one of these modules needs to be changed.

### Table 2a - Cyclic Dependencies Overview

Show the top 40 cyclic dependencies sorted by the most promising to resolve first. This is done by calculating the number of forward dependencies (first cycle participant to second cycle participant) in relation to backward dependencies (second cycle participant back to first cycle participant). The higher this rate (approaching 1), the easier it should be to resolve the cycle by focussing on the few backward dependencies.

Only the top 40 entries are shown. The whole table can be found in the following CSV report:  
`Cyclic_Dependencies_for_Typescript`

**Columns:**
- *projectFileName* identifies the project of the first participant of the cycle
- *modulePathName* identifies the module of the first participant of the cycle
- *dependentProjectFileName* identifies the project of the second participant of the cycle
- *dependentModulePathName* identifies the module of the second participant of the cycle
- *forwardToBackwardBalance* is between 0 and 1. High for many forward and few backward dependencies.
- *numberForward* contains the number of dependencies from the first participant of the cycle to the second one
- *numberBackward* contains the number of dependencies from the second participant of the cycle back to the first one
- *someForwardDependencies* lists some forward dependencies in the text format "type1 -> type2"
- *backwardDependencies* lists the backward dependencies in the format "type1 <- type2" that are recommended to get resolved

In [14]:
cyclic_dependencies = query_cypher_to_data_frame("../cypher/Cyclic_Dependencies/Cyclic_Dependencies_for_Typescript.cypher")
cyclic_dependencies.head(40)

,projectFileName,moduleName,dependentProjectFileName,dependentModulePathName,forwardToBackwardBalance,numberForward,numberBackward,forwardDependencyExamples,backwardDependencyExamples
0,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,0.750000,7,1,"[createStaticHandler->getRouteInstrumentationUpdates, createRouter->getRouteInstrumentationUpdates, createRouter->instrumentClientSideRouter, RouterInit->unstable_ClientInstrumentation, createStaticHandler->unstable_InstrumentRouteFunction, createRouter->unstable_InstrumentRouteFunction, createR...",[Router<-instrumentClientSideRouter]
1,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,0.750000,7,1,"[createStaticHandlerDataRoutes->DataRouteObject, createStaticHandlerDataRoutes->replace, createStaticHandlerDataRoutes->MiddlewareFunction, createStaticHandlerDataRoutes->redirectDocument, createStaticHandlerDataRoutes->SingleFetchRedirectSymbol, createStaticHandlerDataRoutes->redirect, createSt...",[ServerRouteManifest<-ServerBuild]
2,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,0.707317,35,6,"[RouterContextProvider->RouterContext, createContext->RouterContext, redirect->redirect, createStaticHandler->RedirectResult, createStaticHandler->isRouteErrorResponse, createStaticHandler->ResultType, matchRSCServerRequest->stripBasename, createStaticHandler->ErrorResult, matchRSCServerRequest-...","[data<-convertRouteMatchToUiMatch, RouterContext<-createContext, MiddlewareNextFunction<-MiddlewareFunction, MiddlewareFunction<-BaseRouteObject, RouterContext<-RouterContextProvider, MiddlewareFunction<-RouteObject]"
3,react-router,./lib/server-runtime/data.ts,react-router,./index.ts,0.666667,5,1,"[callRouteHandler->LoaderFunctionArgs, callRouteHandler->ActionFunction, callRouteHandler->LoaderFunction, callRouteHandler->ActionFunctionArgs, callRouteHandler->DataWithResponseInit]",[AppLoadContext<-RequestHandler]
4,react-router,./lib/dom/ssr/fog-of-war.ts,react-router,./index.ts,0.636364,18,4,"[getPatchRoutesOnNavigationFunction->PatchRoutesOnNavigationFunction, fetchAndApplyManifestPatches->createClientRoutes, getPatchRoutesOnNavigationFunction->Router, getPartialManifest->Router, useFogOFWarDiscovery->Router, fetchAndApplyManifestPatches->Router, fetchAndApplyManifestPatches->Assets...","[fetchAndApplyManifestPatches<-useFogOFWarDiscovery, isFogOfWarEnabled<-useFogOFWarDiscovery, fetchAndApplyManifestPatches<-getPatchRoutesOnNavigationFunction, isFogOfWarEnabled<-getPatchRoutesOnNavigationFunction]"
5,react-router,./lib/server-runtime/sessions.ts,react-router,./index-react-server.ts,0.600000,12,3,"[createSessionStorage->createCookie, SessionIdStorageStrategy->CookieSignatureOptions, createSessionStorage->SessionIdStorageStrategy, createSessionStorage->Cookie, warnOnceAboutSigningSessionCookie->Cookie, SessionIdStorageStrategy->Cookie, createSessionStorage->SessionStorage, SessionStorage->...","[createSessionStorage<-createMemorySessionStorage, warnOnceAboutSigningSessionCookie<-createCookieSessionStorage, createSession<-createCookieSessionStorage]"
6,react-router,./lib/server-runtime/sessions.ts,react-router,./index.ts,0.600000,12,3,"[SessionIdStorageStrategy->CookieSignatureOptions, createSessionStorage->SessionStorage, createSessionStorage->SessionIdStorageStrategy, createSessionStorage->isCookie, createSessionStorage->Cookie, warnOnceAboutSigningSessionCookie->Cookie, SessionIdStorageStrategy->Cookie, SessionStorage->Sess...","[warnOnceAboutSigningSessionCookie<-createCookieSessionStorage, createSession<-createCookieSessionStorage, createSessionStorage<-createMemorySessionStorage]"
7,react-router-dev,./vite/plugin.ts,react-router-dev,./vite/styles.ts,0.500000,3,1,"[reactRouterVitePlugin->isCssModulesFile, reactRouterVitePlugin->getCssStringFromViteDevModuleCode, reactRouterVitePlugin->getStylesForPathname]",[LoadCssContents<-getStylesForPathname]
8,react-router,./lib/router/router.ts,react-router,./index.ts,0.456311,75,28,"[createStaticHandler->DataStrategyMatch, createRouter->DataStrategyMatch, Router->To, RouterInit->PatchRoutesOnNavigationFunction, Router->RouterSubscriber, createRouter->RouterSubscriber, Fetcher->FormEncType, Navigation->FormEncType, FetcherStates->FormEncType]","[RouterState<-DataRouterStateContext, Router<-DataRouterStateContext, Router<-useFogOFWarDiscovery, RouterState<-getPatchRoutesOnNavigationFunction, Router<-getPatchRoutesOnNavigationFunction, RouterState<-Router, Blocker<-Router, GetScrollRestorationKeyFunction<-Router, RouterSubscriber<-Router]"
9,react-router,./lib/rsc/server.rsc.ts,react-router,./index.ts,0.454545,32,12,"[matchRSCServerRequest->DecodeReplyFunction, RSCRenderPayload->RSCRouteMatch, redirectDocument->RedirectFunction, replace->RedirectFunction, redirect->RedirectFunction, matchRSCServerRequest->DecodeActionFunction, Await->Await, RSCRenderPayload->RSCRouteManifest, RSCManifestPayload->RSCRouteMani...","[matchRSCServerRequest<-unstable_matchRSCServerRequest, RSCRouteManifest<-RSCRouteMatch, RSCPayload<-RSCMatch, RSCRouteManifest<-RSCManifestPayload, RSCActionPayload<-RSCPayload, RSCRenderPayload<-RSCPayload, RSCManifestPayload<-RSCPayload, RSCRedirectPayload<-RSCPayload, RSCRouteConfigEntry<-RS..."
10,react-router,./lib/server-runtime/server.ts,react-router,./index.ts,0.428571,5,2,"[RequestHandler->AppLoadContext, createRequestHandler->ServerBuild, CreateRequestHandlerFunction->ServerBuild, createRequestHandler->CreateRequestHandlerFunction, CreateRequestHandlerFunction->RequestHandler]","[RequestHandler<-CreateRequestHandlerFunction, CreateRequestHandlerFunction<-createRequestHandler]"
11,react-router,./index.ts,react-router,./lib/router/history.ts,0.382353,47,21,"[createMemoryHistory->MemoryHistoryOptions, createHashHistory->createLocation, createRouter->createLocation, createBrowserHistory->createLocation, createMemoryHistory->createLocation, createBrowserHistory->UrlHistoryOptions, createHashHistory->UrlHistoryOptions, createHashHistory->createPath, ge...","[InitialEntry<-MemoryHistoryOptions, To<-createLocation, Location<-createLocation, Path<-createLocation, parsePath<-createLocation, parsePath<-createMemoryHistory, createPath<-createMemoryHistory, Action<-createMemoryHistory, To<-createBrowserURLImpl]"
12,react-router,./lib/dom/ssr/routeModules.ts,react-router,./index.ts,0.371429,24,11,"[ClientActionFunction->ClientActionFunctionArgs, ClientLoaderFunctionArgs->LoaderFunctionArgs, ClientLoaderFunction->ClientLoaderFunctionArgs, RouteModule->ShouldRevalidateFunction, ServerRouteModule->MiddlewareFunction, RouteModule->MiddlewareFunction, ServerRouteModule->ActionFunction, RouteMo...","[ClientLoaderFunction<-MetaArgs, MetaMatches<-MetaArgs, RouteModules<-useFogOFWarDiscovery, RouteModules<-getPatchRoutesOnNavigationFunction, ClientActionFunction<-RSCRouteManifest, LinksFunction<-RSCRouteManifest, MetaFunction<-RSCRouteManifest, ClientLoaderFunction<-RSCRouteManifest, ClientLoa..."
13,react-router,./index-react-server.ts,react-router,./index.ts,0.364706,58,27,"[createStaticHandler->DataStrategyMatch, matchRSCServerRequest->DecodeReplyFunction, CookieOptions->CookieSignatureOptions, RSCRenderPayload->RSCRouteMatch, redirectDocument->RedirectFunction, replace->RedirectFunction, redirect->RedirectFunction, matchRSCServerRequest->DecodeActionFunction, Awa...","[matchRSCServerRequest<-unstable_matchRSCServerRequest, RSCRouteManifest<-RSCRouteMatch, MiddlewareNextFunction<-MiddlewareFunction, createCookie<-createCookieSessionStorage, Cookie<-createCookieSessionStorage, SessionStorage<-createCookieSessionStorage, isCookie<-createCookieSessionStorage, Rou..."
14,react-router,./dom-export.ts,react-router,./index.ts,0.333333,6,3,"[RSCRenderPayload->RSCRouteMatch, RSCRenderPayload->RSCRouteManifest, RSCManifestPayload->RSCRouteManifest, RSCRenderPayload->Location, RSCPayload->RSCManifestPayload, RSCPayload->RSCRenderPayload]","[RSCPayload<-RSCMatch, RSCManifestPayload<-RSCPayload, RSCRenderPayload<-RSCPayload]"
15,react-router,./index-react-server.ts,react-router,./lib/dom/ssr/routeModules.ts,0.333333,4,2,"[RSCRouteManifest->ClientActionFunction, RSCRouteManifest->LinksFunction, RSCRouteManifest->MetaFunction, RSCRouteManifest->ClientLoaderFunction]","[MiddlewareFunction<-ServerRouteModule, MiddlewareFunction<-RouteModule]"
16,react-router,./index-react-server.ts,react-router,./lib/router/instrumentation.ts,0.333333,2,1,"[createStaticHandler->getRouteInstrumentationUpdates, createStaticHandler->unstable_InstrumentRouteFunction]",[MiddlewareFunction<-getRouteInstrumentationUpdates]
17,react-router-architect,./index.ts,react-router-architect,./server.ts,0.333333,4,2,"[createRequestHandler->createReactRouterRequest, createRequestHandler->RequestHandler, createRequestHandler->GetLoadContextFunction, createRequestHandler->sendReactRouterResponse]","[RequestHandler<-createRequestHandler, GetLoadContextFunction<-createRequestHandler]"
18,react-router,./index.ts,react-router,./lib/types/route-data.ts,0.333333,2,1,"[ClientLoaderFunctionArgs->SerializeFrom, ClientActionFunctionArgs->SerializeFrom]",[AppLoadContext<-ServerDataFunctionArgs]
19,react-router-express,./index.ts,react-router-express,./server.ts,0.333333,4,2,"[createRequestHandler->GetLoadContextFunction, createRequestHandler->sendRemixResponse, createRequestHandler->RequestHandler, createRequestHandler->createRemixRequest]","[GetLoadContextFunction<-createRequestHandler, RequestHandler<-createRequestHandler]"
20,react-router,./index-react-server.ts,react-router,./lib/server-runtime/cookies.ts,0.272727,7,4,"[isCookie->IsCookieFunction, CookieOptions->CookieSignatureOptions, createCookieSessionStorage->createCookie, createCookieSessionStorage->isCookie, createCookie->CookieOptions, createCookieSessionStorage->Cookie, createCookie->Cookie]","[Cookie<-createCookie, CookieOptions<-createCookie, IsCookieFunction<-isCookie, CookieSignatureOptions<-CookieOptions]"
21,react-router,./index.ts,react-router,./lib/server-runtime/cookies.ts,0.272727,7,4,"[isCookie->IsCookieFunction, CookieOptions->CookieSignatureOptions, createCookieSessionStorage->createCookie, createCookieSessionStorage->isCookie, createCookie->CookieOptions, createCookieSessionStorage->Cookie, createCookie->Cookie]","[Cookie<-createCookie, CookieOptions<-createCookie, IsCookieFunction<-isCookie, CookieSignatureOptions<-CookieOptions]"
22,react-router,./lib/dom/dom.ts,react-router,./index.ts,0.272727,7,4,"[createSearchParams->URLSearchParamsInit, SubmitOptions->FetcherSubmitOptions, getSearchParamsForLocation->createSearchParams, defaultMethod->HTMLFormMethod, URLSearchParamsInit->ParamKeyValuePair, createSearchParams->ParamKeyValuePair, getFormSubmissionInfo->SubmitTarget]","[ParamKeyValuePair<-URLSearchParamsInit, ParamKeyValuePair<-createSearchParams, URLSearchParamsInit<-createSearchParams, FetcherSubmitOptions<-SubmitOptions]"
23,react-router-dev,./config/routes.ts,react-router-dev,./routes.ts,0.259259,17,10,"[prefix->route, configRoutesToRouteManifest->route, relative->route, relative->prefix, validateRouteConfig->RouteConfigEntry, layout->RouteConfigEntry, routeConfigEntrySchema->RouteConfigEntry, index->RouteConfigEntry, RouteConfig->RouteConfigEntry]","[index<-relative, prefix<-relative, route<-relative, layout<-relative, RouteConfigEntry<-RouteConfig, RouteConfigEntry<-route, route<-prefix, RouteConfigEntry<-prefix, RouteConfigEntry<-index]"
24,react-router,./index.ts,react-router,./lib/dom/ssr/entry.ts,0.250000,5,3,"[EntryContext->FrameworkContextObject, ServerBuild->AssetsManifest, getPatchRoutesOnNavigationFunction->AssetsManifest, useFogOFWarDiscovery->AssetsManifest, ServerBuild->FutureConfig]","[AssetsManifest<-FrameworkContextObject, RouteModules<-FrameworkContextObject, StaticHandlerContext<-EntryContext]"
25,react-router,./lib/context.ts,react-router,./index.ts,0.250000,10,6,"[Navigator->To, DataRouterStateContext->Router, DataRouterContextObject->Router, ViewTransitionContextObject->Location, DataRouterStateContext->RouterState, RouteContextObject->RouteMatch, DataRouterContextObject->StaticHandlerContext, RouteContextObject->RouteObject, Navigator->NavigateOptions]","[ViewTransitionContextObject<-ViewTransitionContext, AwaitContext<-AwaitContextProvider, FetchersContextObject<-FetchersContext, DataRouterContextObject<-DataRouterContext, NavigateOptions<-Navigator, RouteContextObject<-RouteContext]"
26,react-router,./lib/router/instrumentation.ts,react-router,./index.ts,0.166667,14,10,"[getRouteInstrumentationUpdates->LoaderFunctionArgs, getRouteInstrumentationUpdates->DataRouteObject, instrumentClientSideRouter->unstable_InstrumentRouterFunction, unstable_ClientInstrumentation->unstable_InstrumentRouterFunction, getRouteInstrumentationUpdates->MiddlewareFunction, instrumentHa...","[unstable_InstrumentRouteFunction<-unstable_ServerInstrumentation, unstable_InstrumentRequestHandlerFunction<-unstable_ServerInstrumentation, unstable_InstrumentRouteFunction<-unstable_ClientInstrumentation, unstable_InstrumentRouterFunction<-unstable_ClientInstrumentation, unstable_ServerInstru..."
27,react-router-dev,./config.ts,react-router-dev,./config/config.ts,0.142857,4,3,"[ReactRouterConfig->Preset, Preset->ReactRouterConfig, ReactRouterConfig->PrerenderPaths, ReactRouterConfig->ServerBundlesFunction]","[ReactRouterConfig<-Preset, Preset<-ReactRouterConfig, ServerBundlesFunction<-ReactRouterConfig]"
28,react-router,./index.ts,react-router,./lib/router/utils.ts,0.119565,103,81,"[RouterContextProvider->RouterContext, createContext->RouterContext, replace->redirect, redirectDocument->redirect, generatePath->PathParam, createRouter->RedirectResult, BaseRouteObject->ActionFunction, RouteObject->ActionFunction, createRouter->convertRouteMatchToUiMatch]","[RouteMatch<-getPathContributingMatches, RouteObject<-getPathContributingMatches, RedirectFunction<-redirect, UIMatch<-convertRouteMatchToUiMatch, data<-convertRouteMatchToUiMatch, DataRouteMatch<-convertRouteMatchToUiMatch, RouteObject<-LazyRouteObject, PathPattern<-PathMatch, Params<-PathMatch]"
29,react-router,./index-react-server.ts,react-router,./dom-export.ts,0.090909,6,5,"[matchRSCServerRequest->DecodeActionFunction, RSCPayload->RSCManifestPayload, matchRSCServerRequest->DecodeReplyFunction, matchRSCServerRequest->DecodeFormStateFunction, RSCPayload->RSCRenderPayload, RSCMatch->RSCPayload]","[RSCRouteManifest<-RSCManifestPayload, RSCRouteMatch<-RSCRenderPayload, RSCRouteManifest<-RSCRenderPayload, RSCRenderPayload<-RSCPayload, RSCManifestPayload<-RSCPayload]"
30,react-router,./index-react-server.ts,react-router,./lib/router/router.ts,0.066667,8,7,"[createStaticHandler->CreateStaticHandlerOptions, createStaticHandler->StaticHandlerContext, createStaticHandler->isRedirectResponse, createStaticHandler->isMutationMethod, createStaticHandler->StaticHandler, createStaticHandler->getStaticContextFromError, createStaticHandler->isDataWithResponse...","[isRouteErrorResponse<-createRouter, matchRoutes<-createRouter, RouterContextProvider<-createRouter, isRouteErrorResponse<-createStaticHandler, matchRoutes<-createStaticHandler, RouterContextProvider<-createStaticHandler, isRouteErrorResponse<-getStaticContextFromError]"
31,react-router,./index-react-server.ts,react-router,./lib/rsc/server.rsc.ts,0.028571,18,17,"[matchRSCServerRequest->RSCRouteConfigEntry, RSCRouteConfig->RSCRouteConfigEntry, matchRSCServerRequest->isManifestRequest, RSCPayload->RSCActionPayload, RSCPayload->RSCRenderPayload, matchRSCServerRequest->LoadServerActionFunction, matchRSCServerRequest->DecodeActionFunction, RSCRenderPayload->...","[RSCRenderPayload<-RSCActionPayload, RSCRouteMatch<-RSCRenderPayload, RSCRouteManifest<-RSCRenderPayload, RSCRouteConfigEntry<-RSCRouteConfig, RSCRouteManifest<-RSCRouteMatch, DecodeActionFunction<-matchRSCServerRequest, RSCRouteConfigEntry<-matchRSCServerRequest, DecodeReplyFunction<-matchRSCSe..."
32,react-router,./lib/router/links.ts,react-router,./index.ts,0.000000,2,2,"[LinkDescriptor->PageLinkDescriptor, PageLinkDescriptor->HtmlLinkDescriptor]","[HtmlLinkDescriptor<-PageLinkDescriptor, PageLinkDescriptor<-LinkDescriptor]"
33,react-router,./lib/rsc/server.rsc.ts,react-router,./dom-export.ts,0.000000,7,7,"[matchRSCServerRequest->DecodeActionFunction, RSCPayload->RSCManifestPayload, matchRSCServerRequest->DecodeReplyFunction, matchRSCServerRequest->DecodeFormStateFunction, RSCPayload->RSCRenderPayload, RSCActionPayload->RSCRenderPayload, RSCMatch->RSCPayload]","[RSCRouteManifest<-RSCManifestPayload, RSCRouteMatch<-RSCRenderPayload, RSCRouteManifest<-RSCRenderPayload, RSCActionPayload<-RSCPayload, RSCRenderPayload<-RSCPayload, RSCManifestPayload<-RSCPayload, RSCRedirectPayload<-RSCPayload]"
34,react-router,./lib/server-runtime/build.ts,react-router,./index.ts,0.000000,6,6,"[ServerEntryModule->HandleErrorFunction, ServerEntryModule->HandleDataRequestFunction, ServerEntryModule->unstable_ServerInstrumentation, ServerBuild->AssetsManifest, ServerEntryModule->HandleDocumentRequestFunction, ServerBuild->ServerEntryModule]","[ServerEntryModule<-ServerBuild, ServerBuild<-CreateRequestHandlerFunction, HandleDocumentRequestFunction<-ServerEntryModule, HandleDataRequestFunction<-ServerEntryModule, HandleErrorFunction<-ServerEntryModule, ServerBuild<-createRequestHandler]"
35,react-router-node,./server.ts,react-router-node,./index.ts,0.000000,1,1,[createRequestListener->RequestListenerOptions],[RequestListenerOptions<-createRequestListener]
36,react-router-cloudflare,./worker.ts,react-router-cloudflare,./index.ts,0.000000,5,5,"[createRequestHandler->RequestHandler, createPagesFunctionHandler->createRequestHandler, createPagesFunctionHandler->createPagesFunctionHandlerParams, createRequestHandler->createPagesFunctionHandlerParams, createPagesFunctionHandlerParams->GetLoadContextFunction]","[RequestHandler<-createRequestHandler, createPagesFunctionHandlerParams<-createRequestHandler, GetLoadContextFunction<-createPagesFunctionHandlerParams, createPagesFunctionHandlerParams<-createPagesFunctionHandler, createRequestHandler<-createPagesFunctionHandler]"

### Table 2b - Cyclic Dependencies Break Down

Lists modules with cyclic dependencies with every dependency in a separate row sorted by the most promising dependency first.

Only the top 40 entries are shown. The whole table can be found in the following CSV report:  
`Cyclic_Dependencies_Breakdown_for_Typescript`

**Columns in addition to Table 2a:**
- *dependency* shows the cycle dependency in the text format "type1 -> type2" (forward) or "type2<-type1" (backward)

In [15]:
cyclic_dependencies_breakdown = query_cypher_to_data_frame("../cypher/Cyclic_Dependencies/Cyclic_Dependencies_Breakdown_for_Typescript.cypher",limit=40)
cyclic_dependencies_breakdown

,projectFileName,moduleName,dependentProjectFileName,dependentModulePathName,dependency,forwardToBackwardBalance,numberForward,numberBackward
0,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,RouterInit->unstable_ClientInstrumentation,0.750000,7,1
1,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,createRouter->instrumentClientSideRouter,0.750000,7,1
2,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,createRouter->getRouteInstrumentationUpdates,0.750000,7,1
3,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,Router<-instrumentClientSideRouter,0.750000,7,1
4,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,createRouter->unstable_InstrumentRouterFunction,0.750000,7,1
5,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,createStaticHandler->unstable_InstrumentRouteFunction,0.750000,7,1
6,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,createStaticHandler->getRouteInstrumentationUpdates,0.750000,7,1
7,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,createRouter->unstable_InstrumentRouteFunction,0.750000,7,1
8,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,createStaticHandlerDataRoutes->decodeViaTurboStream,0.750000,7,1
9,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,createStaticHandlerDataRoutes->SingleFetchRedirectSymbol,0.750000,7,1
10,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,createStaticHandlerDataRoutes->redirect,0.750000,7,1
11,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,createStaticHandlerDataRoutes->MiddlewareFunction,0.750000,7,1
12,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,createStaticHandlerDataRoutes->redirectDocument,0.750000,7,1
13,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,ServerRouteManifest<-ServerBuild,0.750000,7,1
14,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,createStaticHandlerDataRoutes->replace,0.750000,7,1
15,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,createStaticHandlerDataRoutes->DataRouteObject,0.750000,7,1
16,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,matchRSCServerRequest->RouteMatch,0.707317,35,6
17,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createStaticHandler->ResultType,0.707317,35,6
18,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createStaticHandler->RouteMatch,0.707317,35,6
19,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createContext->RouterContext,0.707317,35,6
20,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,MiddlewareNextFunction<-MiddlewareFunction,0.707317,35,6
21,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,RouterContext<-RouterContextProvider,0.707317,35,6
22,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,redirect->redirect,0.707317,35,6
23,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,MiddlewareFunction<-BaseRouteObject,0.707317,35,6
24,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,MiddlewareFunction<-RouteObject,0.707317,35,6
25,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,RouterContextProvider->RouterContext,0.707317,35,6
26,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createStaticHandler->RedirectResult,0.707317,35,6
27,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createStaticHandler->isRouteErrorResponse,0.707317,35,6
28,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,matchRSCServerRequest->stripBasename,0.707317,35,6
29,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createStaticHandler->ErrorResult,0.707317,35,6
30,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,matchRoutes->RouteMatch,0.707317,35,6
31,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,data->DataWithResponseInit,0.707317,35,6
32,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createStaticHandler->SuccessResult,0.707317,35,6
33,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createStaticHandler->DataStrategyResult,0.707317,35,6
34,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,data<-convertRouteMatchToUiMatch,0.707317,35,6
35,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createStaticHandler->getRoutePattern,0.707317,35,6
36,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,RouterContext<-createContext,0.707317,35,6
37,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,redirectDocument->redirectDocument,0.707317,35,6
38,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,createStaticHandler->convertRoutesToDataRoutes,0.707317,35,6
39,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,redirectDocument->RedirectFunction,0.707317,35,6

### Table 2c - Cyclic Dependencies Break Down - Backward Dependencies Only

Lists modules with cyclic dependencies with every dependency in a separate row sorted by the most promising  dependency first. This table only contains the backward dependencies from the second participant of the cycle back to the first one that are the most promising to resolve.

Only the top 40 entries are shown. The whole table can be found in the following CSV report:  
`Cyclic_Dependencies_Breakdown_BackwardOnly_for_Typescript`

In [16]:
cyclic_dependencies_breakdown_backward = query_cypher_to_data_frame("../cypher/Cyclic_Dependencies/Cyclic_Dependencies_Breakdown_Backward_Only_for_Typescript.cypher",limit=40)
cyclic_dependencies_breakdown_backward

,projectFileName,moduleName,dependentProjectFileName,dependentModulePathName,dependency,forwardToBackwardBalance,numberForward,numberBackward
0,react-router,./lib/router/router.ts,react-router,./lib/router/instrumentation.ts,Router<-instrumentClientSideRouter,0.750000,7,1
1,react-router,./lib/server-runtime/routes.ts,react-router,./index.ts,ServerRouteManifest<-ServerBuild,0.750000,7,1
2,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,data<-convertRouteMatchToUiMatch,0.707317,35,6
3,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,RouterContext<-createContext,0.707317,35,6
4,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,MiddlewareNextFunction<-MiddlewareFunction,0.707317,35,6
5,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,MiddlewareFunction<-BaseRouteObject,0.707317,35,6
6,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,RouterContext<-RouterContextProvider,0.707317,35,6
7,react-router,./index-react-server.ts,react-router,./lib/router/utils.ts,MiddlewareFunction<-RouteObject,0.707317,35,6
8,react-router,./lib/server-runtime/data.ts,react-router,./index.ts,AppLoadContext<-RequestHandler,0.666667,5,1
9,react-router,./lib/dom/ssr/fog-of-war.ts,react-router,./index.ts,isFogOfWarEnabled<-useFogOFWarDiscovery,0.636364,18,4
10,react-router,./lib/dom/ssr/fog-of-war.ts,react-router,./index.ts,fetchAndApplyManifestPatches<-useFogOFWarDiscovery,0.636364,18,4
11,react-router,./lib/dom/ssr/fog-of-war.ts,react-router,./index.ts,fetchAndApplyManifestPatches<-getPatchRoutesOnNavigationFunction,0.636364,18,4
12,react-router,./lib/dom/ssr/fog-of-war.ts,react-router,./index.ts,isFogOfWarEnabled<-getPatchRoutesOnNavigationFunction,0.636364,18,4
13,react-router,./lib/server-runtime/sessions.ts,react-router,./index.ts,createSessionStorage<-createMemorySessionStorage,0.600000,12,3
14,react-router,./lib/server-runtime/sessions.ts,react-router,./index.ts,createSession<-createCookieSessionStorage,0.600000,12,3
15,react-router,./lib/server-runtime/sessions.ts,react-router,./index.ts,warnOnceAboutSigningSessionCookie<-createCookieSessionStorage,0.600000,12,3
16,react-router,./lib/server-runtime/sessions.ts,react-router,./index-react-server.ts,createSessionStorage<-createMemorySessionStorage,0.600000,12,3
17,react-router,./lib/server-runtime/sessions.ts,react-router,./index-react-server.ts,createSession<-createCookieSessionStorage,0.600000,12,3
18,react-router,./lib/server-runtime/sessions.ts,react-router,./index-react-server.ts,warnOnceAboutSigningSessionCookie<-createCookieSessionStorage,0.600000,12,3
19,react-router-dev,./vite/plugin.ts,react-router-dev,./vite/styles.ts,LoadCssContents<-getStylesForPathname,0.500000,3,1
20,react-router,./lib/router/router.ts,react-router,./index.ts,Fetcher<-Router,0.456311,75,28
21,react-router,./lib/router/router.ts,react-router,./index.ts,FutureConfig<-Router,0.456311,75,28
22,react-router,./lib/router/router.ts,react-router,./index.ts,StaticHandlerContext<-StaticHandler,0.456311,75,28
23,react-router,./lib/router/router.ts,react-router,./index.ts,BlockerFunction<-Router,0.456311,75,28
24,react-router,./lib/router/router.ts,react-router,./index.ts,RouterSubscriber<-Router,0.456311,75,28
25,react-router,./lib/router/router.ts,react-router,./index.ts,GetScrollRestorationKeyFunction<-Router,0.456311,75,28
26,react-router,./lib/router/router.ts,react-router,./index.ts,Blocker<-Router,0.456311,75,28
27,react-router,./lib/router/router.ts,react-router,./index.ts,GetScrollPositionFunction<-Router,0.456311,75,28
28,react-router,./lib/router/router.ts,react-router,./index.ts,IDLE_FETCHER<-createRouter,0.456311,75,28
29,react-router,./lib/router/router.ts,react-router,./index.ts,StaticHandlerContext<-EntryContext,0.456311,75,28
30,react-router,./lib/router/router.ts,react-router,./index.ts,RouterState<-Router,0.456311,75,28
31,react-router,./lib/router/router.ts,react-router,./index.ts,Router<-getPatchRoutesOnNavigationFunction,0.456311,75,28
32,react-router,./lib/router/router.ts,react-router,./index.ts,BlockerFunction<-createRouter,0.456311,75,28
33,react-router,./lib/router/router.ts,react-router,./index.ts,RouterState<-getPatchRoutesOnNavigationFunction,0.456311,75,28
34,react-router,./lib/router/router.ts,react-router,./index.ts,RouterSubscriber<-createRouter,0.456311,75,28
35,react-router,./lib/router/router.ts,react-router,./index.ts,Router<-useFogOFWarDiscovery,0.456311,75,28
36,react-router,./lib/router/router.ts,react-router,./index.ts,IDLE_BLOCKER<-createRouter,0.456311,75,28
37,react-router,./lib/router/router.ts,react-router,./index.ts,isMutationMethod<-createRouter,0.456311,75,28
38,react-router,./lib/router/router.ts,react-router,./index.ts,IDLE_NAVIGATION<-createRouter,0.456311,75,28
39,react-router,./lib/router/router.ts,react-router,./index.ts,Router<-DataRouterStateContext,0.456311,75,28

## 3 - Module Usage

### Table 3a - Elements that are used by multiple modules

This table shows the top 40 modules that are used by the highest number of different modules. The whole table can be found in the CSV report `WidelyUsedTypescriptElements`.

In [17]:
elements_used_by_many_modules=query_cypher_to_data_frame("../cypher/Internal_Dependencies/List_elements_that_are_used_by_many_different_modules_for_Typescript.cypher", limit=40)
elements_used_by_many_modules

,fullQualifiedDependentElementName,dependentElementModuleName,dependentElementName,dependentElementLabels,numberOfUsingModules
0,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/history.ts"".Location",history.ts,Location,Interface,9
1,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router-dev/config/routes.ts"".RouteManifestEntry",routes.ts,RouteManifestEntry,Interface,9
2,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router-dev/vite/vite.ts"".getVite",vite.ts,getVite,Function,9
3,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router-dev/vite/vite.ts"".preloadVite",vite.ts,preloadVite,Function,9
4,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".RouteMatch",utils.ts,RouteMatch,Interface,8
5,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/dom/ssr/routeModules.ts"".RouteModules",routeModules.ts,RouteModules,Interface,7
6,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/router.ts"".StaticHandlerContext",router.ts,StaticHandlerContext,Interface,7
7,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/create-react-router/utils.ts"".color",utils.ts,color,Variable,7
8,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".stripBasename",utils.ts,stripBasename,Function,7
9,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".DataWithResponseInit",utils.ts,DataWithResponseInit,Class,6
10,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".ErrorResponseImpl",utils.ts,ErrorResponseImpl,Class,6
11,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/dom/ssr/entry.ts"".FutureConfig",entry.ts,FutureConfig,Interface,6
12,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".Params",utils.ts,Params,TypeAlias,6
13,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".RouteObject",utils.ts,RouteObject,TypeAlias,6
14,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".matchRoutes",utils.ts,matchRoutes,Function,6
15,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/dom/ssr/entry.ts"".AssetsManifest",entry.ts,AssetsManifest,Interface,5
16,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/cookies.ts"".Cookie",cookies.ts,Cookie,Interface,5
17,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".DataRouteMatch",utils.ts,DataRouteMatch,Interface,5
18,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".DataRouteObject",utils.ts,DataRouteObject,TypeAlias,5
19,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".LoaderFunction",utils.ts,LoaderFunction,TypeAlias,5
20,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".LoaderFunctionArgs",utils.ts,LoaderFunctionArgs,Interface,5
21,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".MiddlewareFunction",utils.ts,MiddlewareFunction,TypeAlias,5
22,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/history.ts"".Path",history.ts,Path,Interface,5
23,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/rsc/server.rsc.ts"".RSCRenderPayload",server.rsc.ts,RSCRenderPayload,TypeAlias,5
24,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/rsc/server.rsc.ts"".RSCRouteManifest",server.rsc.ts,RSCRouteManifest,TypeAlias,5
25,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router-dev/config/routes.ts"".RouteManifest",routes.ts,RouteManifest,Interface,5
26,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/router.ts"".Router",router.ts,Router,Interface,5
27,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".RouterContextProvider",utils.ts,RouterContextProvider,Class,5
28,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/sessions"".SessionStorage",sessions,SessionStorage,ExternalDeclaration,5
29,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".ShouldRevalidateFunction",utils.ts,ShouldRevalidateFunction,Interface,5
30,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/history.ts"".To",history.ts,To,TypeAlias,5
31,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".TrackedPromise",utils.ts,TrackedPromise,Interface,5
32,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/history.ts"".invariant",history.ts,invariant,Function,5
33,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".isRouteErrorResponse",utils.ts,isRouteErrorResponse,Function,5
34,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".redirect",utils.ts,redirect,Variable,5
35,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".ActionFunction",utils.ts,ActionFunction,Interface,4
36,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".ActionFunctionArgs",utils.ts,ActionFunctionArgs,Interface,4
37,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/data.ts"".AppLoadContext",data.ts,AppLoadContext,Interface,4
38,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/dom/ssr/routeModules.ts"".ClientActionFunction",routeModules.ts,ClientActionFunction,TypeAlias,4
39,"""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/dom/ssr/routeModules.ts"".ClientLoaderFunction",routeModules.ts,ClientLoaderFunction,TypeAlias,4

### Table 3b - Elements that are used by multiple modules

This table shows the top 30 modules that only use a few (compared to all existing) elements of another module.
The whole table can be found in the CSV report `ModuleElementsUsageTypescript`.

In [18]:
used_packages_of_dependent_artifact=query_cypher_to_data_frame("../cypher/Internal_Dependencies/How_many_elements_compared_to_all_existing_are_used_by_dependent_modules_for_Typescript.cypher",limit=30)
used_packages_of_dependent_artifact

,sourceModuleName,dependentModuleName,dependentElementsCount,dependentModuleElementsCount,elementUsagePercentage,dependentElementFullNameExamples,dependentElementNameExamples
0,memoryStorage,react-router,1,179,0.005587,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/sessions"".SessionStorage]",[SessionStorage]
1,urls,react-router,1,171,0.005848,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/history.ts"".Path]",[Path]
2,route-data,react-router,1,171,0.005848,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/data.ts"".AppLoadContext]",[AppLoadContext]
3,mode,react-router,1,171,0.005848,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/mode.ts"".ServerMode]",[ServerMode]
4,links,utils,1,86,0.011628,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".DataRouteMatch]",[DataRouteMatch]
5,headers,utils,1,86,0.011628,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".DataRouteMatch]",[DataRouteMatch]
6,urls,utils,1,86,0.011628,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".stripBasename]",[stripBasename]
7,entry,utils,1,86,0.011628,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".RouteManifest]",[RouteManifest]
8,internal,react-router,2,171,0.011696,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/links.ts"".LinkDescriptor, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/sourc...","[LinkDescriptor, MetaDescriptor]"
9,route-module-annotations,react-router,2,171,0.011696,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/links.ts"".LinkDescriptor, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/sourc...","[LinkDescriptor, MetaDescriptor]"
10,route-modules,react-router,3,179,0.016760,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/rsc/server.rsc.ts"".RSCRenderPayload, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/s...","[RSCRenderPayload, RSCRouteManifest, RouteModules]"
11,entry,react-router,3,171,0.017544,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/dom/ssr/entry.ts"".AssetsManifest, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/sour...","[AssetsManifest, StaticHandlerContext, RouteModules]"
12,cookies,react-router,4,179,0.022346,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/cookies.ts"".CookieSignatureOptions, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-r...","[CookieSignatureOptions, IsCookieFunction, Cookie, CookieOptions]"
13,cookieStorage,react-router,4,179,0.022346,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/cookies.ts"".createCookie, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13...","[createCookie, Cookie, SessionStorage, isCookie]"
14,errors,react-router,4,179,0.022346,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".isRouteErrorResponse, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2...","[isRouteErrorResponse, DataWithResponseInit, ServerMode, ErrorResponseImpl]"
15,routeMatching,react-router,4,179,0.022346,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".matchRoutes, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/r...","[matchRoutes, Params, RouteMatch, RouteObject]"
16,dom,utils,2,86,0.023256,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".stripBasename, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source...","[stripBasename, HTMLFormMethod]"
17,headers,react-router,4,171,0.023392,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/build.ts"".ServerBuild, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/...","[ServerBuild, HeadersFunction, StaticHandlerContext, DataRouteMatch]"
18,dom-export,react-router,5,179,0.027933,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/rsc/server.rsc.ts"".RSCRenderPayload, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/s...","[RSCRenderPayload, RSCRouteMatch, RSCManifestPayload, RSCRouteManifest]"
19,data,react-router,5,171,0.029240,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".LoaderFunctionArgs, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/s...","[LoaderFunctionArgs, ActionFunction, LoaderFunction, ActionFunctionArgs]"
20,headers,router,1,34,0.029412,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/router.ts"".StaticHandlerContext]",[StaticHandlerContext]
21,entry,router,1,34,0.029412,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/router.ts"".StaticHandlerContext]",[StaticHandlerContext]
22,instrumentation,router,1,34,0.029412,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/router.ts"".Router]",[Router]
23,errors,router,1,34,0.029412,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/router.ts"".isDataWithResponseInit]",[isDataWithResponseInit]
24,context,utils,3,86,0.034884,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".RouteMatch, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/re...","[RouteMatch, RouteObject, TrackedPromise]"
25,dom,react-router,6,171,0.035088,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/dom/dom.ts"".URLSearchParamsInit, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/sourc...","[URLSearchParamsInit, FetcherSubmitOptions, createSearchParams, HTMLFormMethod]"
26,build,react-router,6,171,0.035088,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/server-runtime/build.ts"".HandleErrorFunction, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router...","[HandleErrorFunction, HandleDataRequestFunction, unstable_ServerInstrumentation, AssetsManifest]"
27,links,react-router,6,171,0.035088,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/links.ts"".PageLinkDescriptor, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/s...","[PageLinkDescriptor, HtmlLinkDescriptor, Location, AssetsManifest]"
28,create-react-router,utils,1,28,0.035714,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/create-react-router/utils.ts"".log]",[log]
29,routes,react-router,7,179,0.039106,"[""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/source/react-router-7.13.2/packages/react-router/lib/router/utils.ts"".MiddlewareFunction, ""/home/runner/work/code-graph-analysis-examples/code-graph-analysis-examples/temp/react-router-7.13.2/s...","[MiddlewareFunction, DataRouteObject, replace, redirectDocument]"

### Table 3c - Distance distribution between dependent files

This table shows the file directory distance distribution between dependent files. Intuitively, the distance is given by the fewest number of change directory commands needed to navigate between a file and a dependency it uses. Those are aggregate to see how many dependent files are in the same directory, how many are just one change directory command apart, and so on.

In [19]:
query_first_non_empty_cypher_to_data_frame("../cypher/Internal_Dependencies/Get_file_distance_as_shortest_contains_path_for_dependencies.cypher",
                                           "../cypher/Internal_Dependencies/Set_file_distance_as_shortest_contains_path_for_dependencies.cypher", limit=20)

,dependency.fileDistanceAsFewestChangeDirectoryCommands,numberOfDependencies,numberOfDependencyUsers,numberOfDependencyProviders,examples
0,0,149,68,86,"[./index.ts uses ./copy-template.ts, ./index.ts uses ./loading-indicator.ts, ./index.ts uses ./prompt.ts, ./prompt.ts uses ./prompts-confirm.ts]"
1,3,39,22,30,"[./index.ts uses ./sessions/arcTableSessionStorage.ts, ./lib/errors.ts uses ./index.ts, ./lib/context.ts uses ./index.ts, ./lib/server-runtime/single-fetch.ts uses ./lib/actions.ts]"
2,4,121,43,40,"[./lib/rsc/server.rsc.ts uses ./dom-export.ts, ./lib/rsc/route-modules.ts uses ./dom-export.ts, ./lib/rsc/server.rsc.ts uses ./index-react-server-client.ts, ./lib/rsc/route-modules.ts uses ./index-react-server.ts]"
3,5,50,23,18,"[./lib/server-runtime/sessions/memoryStorage.ts uses ./index-react-server.ts, ./lib/dom/ssr/fog-of-war.ts uses ./index-react-server.ts, ./lib/dom/ssr/routeModules.ts uses ./index-react-server.ts, ./lib/server-runtime/sessions/cookieStorage.ts uses ./index-react-server.ts]"
4,6,1,1,1,[./lib/server-runtime/single-fetch.ts uses ./vendor/turbo-stream-v2/turbo-stream.ts]