# Internal Dependencies
<br>  

### References
- [Analyze java package metrics in a graph database](https://joht.github.io/johtizen/data/2023/04/21/java-package-metrics-analysis.html)
- [Calculate metrics](https://101.jqassistant.org/calculate-metrics/index.html)
- [Neo4j Python Driver](https://neo4j.com/docs/api/python-driver/current)

In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plot
from neo4j import GraphDatabase

In [2]:
# Please set the environment variable "NEO4J_INITIAL_PASSWORD" in your shell 
# before starting jupyter notebook to provide the password for the user "neo4j". 
# It is not recommended to hardcode the password into jupyter notebook for security reasons.

driver = GraphDatabase.driver(uri="bolt://localhost:7687", auth=("neo4j", os.environ.get("NEO4J_INITIAL_PASSWORD")))
driver.verify_connectivity()

In [3]:
def get_cypher_query_from_file(cypher_file_name : str):
    with open(cypher_file_name) as file:
        return ' '.join(file.readlines())


def query_cypher_to_data_frame(filename : str, limit: int = -1):
    """
    Execute the Cypher query of the given file and returns the result.
    filename : str : The name of the file containing the Cypher query
    limit : int : The optional limit of rows to optimize the query. Default = -1 = no limit
    """
    cypher_query = get_cypher_query_from_file(filename)
    if limit > 0:
        cypher_query = "{query}\nLIMIT {row_limit}".format(query = cypher_query, row_limit = limit)
    records, summary, keys = driver.execute_query(cypher_query)
    return pd.DataFrame([r.values() for r in records], columns=keys)


def query_first_non_empty_cypher_to_data_frame(*filenames : str, limit: int = -1):
    """
    Executes the Cypher queries of the given files and returns the first result that is not empty.
    If all given file names result in empty results, the last (empty) result will be returned.
    By additionally specifying "limit=" the "LIMIT" keyword will appended to query so that only the first results get returned.
    """    
    result=pd.DataFrame()
    for filename in filenames:
        result=query_cypher_to_data_frame(filename, limit)
        if not result.empty:
            return result
    return result

In [4]:
#The following cell uses the build-in %html "magic" to override the CSS style for tables to a much smaller size.
#This is especially needed for PDF export of tables with multiple columns.

In [5]:
%%html
<style>
/* CSS style for smaller dataframe tables. */
.dataframe th {
    font-size: 8px;
}
.dataframe td {
    font-size: 8px;
}
</style>

In [6]:
# Pandas DataFrame Display Configuration
pd.set_option('display.max_colwidth', 300)

## Artifacts

List the artifacts this notebook is based on. Different sorting variations help finding artifacts by their features and support larger code bases where the list of all artifacts gets too long.

Only the top 30 entries are shown. The whole table can be found in the following CSV report:  
`List_all_Java_artifacts`

In [7]:
artifacts = query_cypher_to_data_frame("../cypher/Internal_Dependencies/List_all_Java_artifacts.cypher")

### Table 1a - Top 30 artifacts with the highest package count

In [8]:
# Sort by number of packages descending
artifacts.sort_values(by=['packages','artifactName'], ascending=[False, True]).reset_index(drop=True).head(30)

,artifactName,packages,types,incomingDependencies,outgoingDependencies
0,axon-messaging-5.0.1.jar,57,570,7,2
1,axon-common-5.0.1.jar,13,150,10,0
2,axon-eventsourcing-5.0.1.jar,7,100,3,4
3,axon-modelling-5.0.1.jar,7,93,2,3
4,axon-spring-boot-autoconfigure-5.0.1.jar,7,70,0,7
5,axon-server-connector-5.0.1.jar,5,72,1,4
6,axon-test-5.0.1.jar,5,73,1,3
7,axon-update-5.0.1.jar,5,23,1,1
8,axon-conversion-5.0.1.jar,4,30,4,1
9,axon-metrics-micrometer-5.0.1.jar,2,13,0,2
10,axon-tracing-opentelemetry-5.0.1.jar,1,5,0,2

### Table 1b - Top 30 artifacts with the highest type count

In [9]:
# Sort by number of types descending
artifacts.sort_values(by=['types','artifactName'], ascending=[False, True]).reset_index(drop=True).head(30)

,artifactName,packages,types,incomingDependencies,outgoingDependencies
0,axon-messaging-5.0.1.jar,57,570,7,2
1,axon-common-5.0.1.jar,13,150,10,0
2,axon-eventsourcing-5.0.1.jar,7,100,3,4
3,axon-modelling-5.0.1.jar,7,93,2,3
4,axon-test-5.0.1.jar,5,73,1,3
5,axon-server-connector-5.0.1.jar,5,72,1,4
6,axon-spring-boot-autoconfigure-5.0.1.jar,7,70,0,7
7,axon-conversion-5.0.1.jar,4,30,4,1
8,axon-update-5.0.1.jar,5,23,1,1
9,axon-metrics-micrometer-5.0.1.jar,2,13,0,2
10,axon-tracing-opentelemetry-5.0.1.jar,1,5,0,2

### Table 1c - Top 30 artifacts with the highest number of incoming dependencies

The following table lists the top 30 artifacts that are used the most by other artifacts (highest count of incoming dependencies, highest in-degree).

In [10]:
# Sort by number of incoming dependencies descending
artifacts.sort_values(by=['incomingDependencies','artifactName'], ascending=[False, True]).reset_index(drop=True).head(30)

,artifactName,packages,types,incomingDependencies,outgoingDependencies
0,axon-common-5.0.1.jar,13,150,10,0
1,axon-messaging-5.0.1.jar,57,570,7,2
2,axon-conversion-5.0.1.jar,4,30,4,1
3,axon-eventsourcing-5.0.1.jar,7,100,3,4
4,axon-modelling-5.0.1.jar,7,93,2,3
5,axon-server-connector-5.0.1.jar,5,72,1,4
6,axon-test-5.0.1.jar,5,73,1,3
7,axon-update-5.0.1.jar,5,23,1,1
8,axon-metrics-micrometer-5.0.1.jar,2,13,0,2
9,axon-spring-boot-autoconfigure-5.0.1.jar,7,70,0,7
10,axon-tracing-opentelemetry-5.0.1.jar,1,5,0,2

### Table 1d - Top 30 artifacts with the highest number of outgoing dependencies

The following table lists the top 30 artifacts that are depending on the highest number of other artifacts (highest count of outgoing dependencies, highest out-degree).

In [11]:
# Sort by number of outgoing dependencies descending
artifacts.sort_values(by=['outgoingDependencies','artifactName'], ascending=[False, True]).reset_index(drop=True).head(30)

,artifactName,packages,types,incomingDependencies,outgoingDependencies
0,axon-spring-boot-autoconfigure-5.0.1.jar,7,70,0,7
1,axon-eventsourcing-5.0.1.jar,7,100,3,4
2,axon-server-connector-5.0.1.jar,5,72,1,4
3,axon-modelling-5.0.1.jar,7,93,2,3
4,axon-test-5.0.1.jar,5,73,1,3
5,axon-messaging-5.0.1.jar,57,570,7,2
6,axon-metrics-micrometer-5.0.1.jar,2,13,0,2
7,axon-tracing-opentelemetry-5.0.1.jar,1,5,0,2
8,axon-conversion-5.0.1.jar,4,30,4,1
9,axon-update-5.0.1.jar,5,23,1,1
10,axon-common-5.0.1.jar,13,150,10,0

### Table 1e - Top 30 artifacts with the lowest package count

In [12]:
# Sort by number of packages ascending
artifacts.sort_values(by=['packages','artifactName'], ascending=[True, True]).reset_index(drop=True).head(30)

,artifactName,packages,types,incomingDependencies,outgoingDependencies
0,axon-tracing-opentelemetry-5.0.1.jar,1,5,0,2
1,axon-metrics-micrometer-5.0.1.jar,2,13,0,2
2,axon-conversion-5.0.1.jar,4,30,4,1
3,axon-server-connector-5.0.1.jar,5,72,1,4
4,axon-test-5.0.1.jar,5,73,1,3
5,axon-update-5.0.1.jar,5,23,1,1
6,axon-eventsourcing-5.0.1.jar,7,100,3,4
7,axon-modelling-5.0.1.jar,7,93,2,3
8,axon-spring-boot-autoconfigure-5.0.1.jar,7,70,0,7
9,axon-common-5.0.1.jar,13,150,10,0
10,axon-messaging-5.0.1.jar,57,570,7,2

### Table 1f - Top 30 artifacts with the lowest type count

In [13]:
# Sort by number of types ascending
artifacts.sort_values(by=['types','artifactName'], ascending=[True, True]).reset_index(drop=True).head(30)

,artifactName,packages,types,incomingDependencies,outgoingDependencies
0,axon-tracing-opentelemetry-5.0.1.jar,1,5,0,2
1,axon-metrics-micrometer-5.0.1.jar,2,13,0,2
2,axon-update-5.0.1.jar,5,23,1,1
3,axon-conversion-5.0.1.jar,4,30,4,1
4,axon-spring-boot-autoconfigure-5.0.1.jar,7,70,0,7
5,axon-server-connector-5.0.1.jar,5,72,1,4
6,axon-test-5.0.1.jar,5,73,1,3
7,axon-modelling-5.0.1.jar,7,93,2,3
8,axon-eventsourcing-5.0.1.jar,7,100,3,4
9,axon-common-5.0.1.jar,13,150,10,0
10,axon-messaging-5.0.1.jar,57,570,7,2

### Table 1g - Top 30 artifacts with the lowest number of incoming dependencies

The following table lists the top 30 artifacts that are used the least by other artifacts (lowest count of incoming dependencies, lowest in-degree).

In [14]:
# Sort by number of incoming dependencies ascending
artifacts.sort_values(by=['incomingDependencies','artifactName'], ascending=[True, True]).reset_index(drop=True).head(30)

,artifactName,packages,types,incomingDependencies,outgoingDependencies
0,axon-metrics-micrometer-5.0.1.jar,2,13,0,2
1,axon-spring-boot-autoconfigure-5.0.1.jar,7,70,0,7
2,axon-tracing-opentelemetry-5.0.1.jar,1,5,0,2
3,axon-server-connector-5.0.1.jar,5,72,1,4
4,axon-test-5.0.1.jar,5,73,1,3
5,axon-update-5.0.1.jar,5,23,1,1
6,axon-modelling-5.0.1.jar,7,93,2,3
7,axon-eventsourcing-5.0.1.jar,7,100,3,4
8,axon-conversion-5.0.1.jar,4,30,4,1
9,axon-messaging-5.0.1.jar,57,570,7,2
10,axon-common-5.0.1.jar,13,150,10,0

### Table 1h - Top 30 artifacts with the lowest number of outgoing dependencies

The following table lists the top 30 artifacts that are depending on the lowest number of other artifacts (lowest count of outgoing dependencies, lowest out-degree).

In [15]:
# Sort by number of outgoing dependencies ascending
artifacts.sort_values(by=['outgoingDependencies','artifactName'], ascending=[True, True]).reset_index(drop=True).head(30)

,artifactName,packages,types,incomingDependencies,outgoingDependencies
0,axon-common-5.0.1.jar,13,150,10,0
1,axon-conversion-5.0.1.jar,4,30,4,1
2,axon-update-5.0.1.jar,5,23,1,1
3,axon-messaging-5.0.1.jar,57,570,7,2
4,axon-metrics-micrometer-5.0.1.jar,2,13,0,2
5,axon-tracing-opentelemetry-5.0.1.jar,1,5,0,2
6,axon-modelling-5.0.1.jar,7,93,2,3
7,axon-test-5.0.1.jar,5,73,1,3
8,axon-eventsourcing-5.0.1.jar,7,100,3,4
9,axon-server-connector-5.0.1.jar,5,72,1,4
10,axon-spring-boot-autoconfigure-5.0.1.jar,7,70,0,7

## Cyclic Dependencies

Cyclic dependencies occur when one package uses a class of another package and vice versa. 
These dependencies can lead to problems when one of these packages needs to be changed.

## Table 2a - Cyclic Dependencies Overview

Show the top 40 cyclic dependencies sorted by the most promising to resolve first. This is done by calculating the number of forward dependencies (first cycle participant to second cycle participant) in relation to backward dependencies (second cycle participant back to first cycle participant). The higher this rate (approaching 1), the easier it should be to resolve the cycle by focussing on the few backward dependencies.

Only the top 40 entries are shown. The whole table can be found in the following CSV report:  
`Cyclic_Dependencies`

**Columns:**
- *artifactName* identifies the artifact of the first participant of the cycle
- *packageName* identifies the package of the first participant of the cycle
- *dependentArtifactName* identifies the artifact of the second participant of the cycle
- *dependentPackageName* identifies the package of the second participant of the cycle
- *forwardToBackwardBalance* is between 0 and 1. High for many forward and few backward dependencies.
- *numberForward* contains the number of dependencies from the first participant of the cycle to the second one
- *numberBackward* contains the number of dependencies from the second participant of the cycle back to the first one
- *someForwardDependencies* lists some forward dependencies in the text format "type1 -> type2"
- *backwardDependencies* lists the backward dependencies in the format "type1 <- type2" that are recommended to get resolved

In [16]:
cyclic_dependencies = query_cypher_to_data_frame("../cypher/Cyclic_Dependencies/Cyclic_Dependencies.cypher")
cyclic_dependencies.head(40)

,artifactName,packageName,dependentArtifactName,dependentPackageName,forwardToBackwardBalance,numberForward,numberBackward,someForwardDependencies,backwardDependencies
0,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,0.959184,48,1,"[HandlerDefinition->MessageStream, InterceptorChainParameterResolverFactory->Context$ResourceKey, InterceptorChainParameterResolverFactory->Message, InterceptorChainParameterResolverFactory->MessageHandlerInterceptorChain, InterceptorChainParameterResolverFactory->MessageStream, AnnotatedHandler...",[SimpleHandlerAttributes->HandlerAttributes]
1,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling,axon-messaging-5.0.1,org.axonframework.messaging.core,0.942857,34,1,"[InterceptingEventSink->MessageDispatchInterceptor, InterceptingEventSink->MessageStream$Single, InterceptingEventSink->MessageStream, InterceptingEventSink->Message, InterceptingEventSink->MessageStream$Empty, EventHandlingComponent->QualifiedName, TerminalEventMessage->MessageType, NoHandlerFo...",[SubscribableEventSource->EventMessage]
2,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,0.933333,29,1,"[SequenceNumberParameterResolverFactory->ParameterResolver, SequenceNumberParameterResolverFactory->AbstractAnnotatedParameterResolverFactory, EventAppenderParameterResolverFactory->ParameterResolver, EventAppenderParameterResolverFactory->ParameterResolverFactory, EventAppenderParameterResolver...",[HandlerTypeResolver->EventHandler]
3,axon-messaging-5.0.1,org.axonframework.messaging.commandhandling.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,0.894737,18,1,"[CommandDispatcherParameterResolverFactoryConfigurationEnhancer->ParameterResolverFactory, MethodCommandHandlerDefinition$MethodCommandHandlingMember->MessageHandlingMember, MethodCommandHandlerDefinition$MethodCommandHandlingMember->WrappedMessageHandlingMember, CommandHandler->MessageHandler, ...",[HandlerTypeResolver->CommandHandler]
4,axon-messaging-5.0.1,org.axonframework.messaging.queryhandling.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,0.875000,15,1,"[QueryResponse->Message, MethodQueryHandlerDefinition$MethodQueryHandlingMember->WrappedMessageHandlingMember, MethodQueryHandlerDefinition$MethodQueryHandlingMember->UnsupportedHandlerException, MethodQueryHandlerDefinition$MethodQueryHandlingMember->MessageHandlingMember, QueryHandlingMember->...",[HandlerTypeResolver->QueryHandler]
5,axon-modelling-5.0.1,org.axonframework.modelling.annotation,axon-modelling-5.0.1,org.axonframework.modelling,0.846154,12,1,"[EntityIdResolverDefinition->EntityIdResolver, InjectEntityParameterResolverFactory->EntityIdResolver, InjectEntityParameterResolverFactory->PropertyBasedEntityIdResolver, InjectEntity->EntityIdResolver, InjectEntityParameterResolver->StateManager, InjectEntityParameterResolver->EntityIdResolver...",[PropertyBasedEntityIdResolver->TargetEntityIdMemberMismatchException]
6,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.processing.streaming.pooled,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,0.666667,15,3,"[PooledStreamingEventProcessorModule->EventProcessorModule$CustomizationPhase, PooledStreamingEventProcessorModule->EventProcessorCustomization, PooledStreamingEventProcessorModule->EventProcessorConfiguration, PooledStreamingEventProcessorModule->EventProcessorModule$EventHandlingPhase, PooledS...","[EventProcessorModule->PooledStreamingEventProcessorConfiguration, EventProcessorModule->PooledStreamingEventProcessorModule, EventProcessingConfigurer->PooledStreamingEventProcessorsConfigurer]"
7,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.processing.subscribing,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,0.666667,15,3,"[SubscribingEventProcessorsConfigurer->EventProcessorModule$CustomizationPhase, SubscribingEventProcessorsConfigurer->EventProcessorModule, SubscribingEventProcessorsConfigurer->EventProcessingConfigurer, SubscribingEventProcessorsConfigurer->EventHandlingComponentsConfigurer$RequiredComponentPh...","[EventProcessorModule->SubscribingEventProcessorConfiguration, EventProcessorModule->SubscribingEventProcessorModule, EventProcessingConfigurer->SubscribingEventProcessorsConfigurer]"
8,axon-common-5.0.1,org.axonframework.common.configuration,axon-common-5.0.1,org.axonframework.common.infra,0.529412,13,4,"[DefaultComponentRegistry->ComponentDescriptor, Components->ComponentDescriptor, Components->DescribableComponent, InstantiatedComponentDefinition->ComponentDescriptor, ComponentRegistry->DescribableComponent, DecoratedComponent->ComponentDescriptor, Component->DescribableComponent, DefaultAxonA...","[JacksonComponentDescriptor->Component, JacksonComponentDescriptor->Component$Identifier, FilesystemStyleComponentDescriptor->Component$Identifier, FilesystemStyleComponentDescriptor->Component]"
9,axon-messaging-5.0.1,org.axonframework.messaging.core.interception.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,0.500000,15,5,"[MessageHandlerInterceptor->MessageHandler, MessageHandlerInterceptorDefinition$InterceptedMessageHandlingMember->MessageHandlingMember, MessageHandlerInterceptorDefinition$InterceptedMessageHandlingMember->WrappedMessageHandlingMember, ResultParameterResolverFactory->ParameterResolverFactory, R...","[ChainedMessageHandlerInterceptorMember->MessageHandlerInterceptorMemberChain, ChainedMessageHandlerInterceptorMember->NoMoreInterceptors, AnnotatedHandlerInspector->MessageInterceptingMember, AnnotatedHandlerInspector->MessageHandlerInterceptorMemberChain, AnnotatedHandlerInspector->NoMoreInter..."
10,axon-messaging-5.0.1,org.axonframework.messaging.core.unitofwork.transaction,axon-messaging-5.0.1,org.axonframework.messaging.core.unitofwork,0.500000,6,2,"[TransactionManager->ProcessingLifecycleHandlerRegistrar, TransactionManager->ProcessingLifecycle, TransactionManager->ProcessingLifecycle$Phase, TransactionManager->ProcessingLifecycle$ErrorHandler, TransactionManager->ProcessingContext, NoTransactionManager->ProcessingLifecycle]","[TransactionalUnitOfWorkFactory->TransactionManager, TransactionalUnitOfWorkFactory->Transaction]"
11,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.event,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,0.428571,5,2,"[EventProcessorControlService->AxonServerConnectionManager, EventProcessorControlService->AxonServerConfiguration$Eventhandling$ProcessorSettings, EventProcessorControlService->AxonServerConfiguration$Eventhandling, AggregateBasedAxonServerEventStorageEngine->MetadataConverter, AxonServerEventSt...","[AxonServerConfigurationEnhancer->AxonServerEventStorageEngineFactory, AxonServerConfigurationEnhancer->EventProcessorControlService]"
12,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.command,0.333333,4,2,"[AxonServerConfigurationEnhancer->AxonServerCommandBusConnector, ErrorCode->AxonServerRemoteCommandHandlingException, ErrorCode->AxonServerCommandDispatchException, ErrorCode->AxonServerNonTransientRemoteCommandHandlingException]","[AxonServerCommandBusConnector->AxonServerConfiguration, CommandConverter->MetadataConverter]"
13,axon-messaging-5.0.1,org.axonframework.messaging.core.configuration,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,0.333333,2,1,"[MessagingConfigurer->EventBusConfigurationDefaults, MessagingConfigurer->EventProcessingConfigurer]",[EventProcessingConfigurer->MessagingConfigurer]
14,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.sequencing,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling,0.333333,8,4,"[SequencingPolicy->EventMessage, ExtractionSequencingPolicy->EventMessage, HierarchicalSequencingPolicy->EventMessage, SequentialPolicy->EventMessage, FallbackSequencingPolicy->EventMessage, FullConcurrencyPolicy->EventMessage, SequentialPerAggregatePolicy->EventMessage, MetadataSequencingPolicy...","[SimpleEventHandlingComponent->SequencingPolicy, SimpleEventHandlingComponent->SequentialPolicy, SimpleEventHandlingComponent->HierarchicalSequencingPolicy, SimpleEventHandlingComponent->SequentialPerAggregatePolicy]"
15,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.query,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,0.200000,6,4,"[AxonServerQueryDispatchException->ErrorCode, FlowControlledResponseSender->ErrorCode, AxonServerQueryBusConnector->AxonServerConfiguration, QueryConverter->ErrorCode, QueryConverter->MetadataConverter, AxonServerQueryBusConnector$AxonServerUpdateCallback->ErrorCode]","[AxonServerConfigurationEnhancer->AxonServerQueryBusConnector, ErrorCode->AxonServerNonTransientRemoteQueryHandlingException, ErrorCode->AxonServerQueryDispatchException, ErrorCode->AxonServerRemoteQueryHandlingException]"
16,axon-modelling-5.0.1,org.axonframework.modelling.entity.annotation,axon-modelling-5.0.1,org.axonframework.modelling.annotation,0.200000,3,2,"[AnnotatedEntityIdResolverDefinition->EntityIdResolverDefinition, AnnotatedEntityIdResolverDefinition->AnnotationBasedEntityIdResolver, AnnotatedEntityMetamodel->AnnotationBasedEntityEvolvingComponent]","[EntityIdResolverDefinition->AnnotatedEntityMetamodel, AnnotationBasedEntityIdResolverDefinition->AnnotatedEntityMetamodel]"
17,axon-messaging-5.0.1,org.axonframework.messaging.core.unitofwork,axon-messaging-5.0.1,org.axonframework.messaging.core,0.157895,11,8,"[UnitOfWork->ApplicationContext, ProcessingContext->ApplicationContext, ProcessingContext->Context, ProcessingContext->Context$ResourceKey, UnitOfWork$UnitOfWorkProcessingContext->Context$ResourceKey, UnitOfWork$UnitOfWorkProcessingContext->ApplicationContext, TransactionalUnitOfWorkFactory->Con...","[DefaultMessageDispatchInterceptorChain->ProcessingContext, DefaultMessageDispatchInterceptorChain$InterceptingDispatcher->ProcessingContext, MessageHandlerInterceptor->ProcessingContext, MessageHandlerInterceptorChain->ProcessingContext, Message->ProcessingContext, SubscribableEventSource->Proc..."
18,axon-modelling-5.0.1,org.axonframework.modelling.entity.child,axon-modelling-5.0.1,org.axonframework.modelling.entity,0.142857,8,6,"[ListEntityChildMetamodel->EntityMetamodel, SingleEntityChildMetamodel->EntityMetamodel, EntityChildMetamodel->EntityMetamodel, AbstractEntityChildMetamodel$Builder->EntityMetamodel, AbstractEntityChildMetamodel->EntityMetamodel, AbstractEntityChildMetamodel->ChildEntityNotFoundException, ListEn...","[PolymorphicEntityMetamodel$Builder->EntityChildMetamodel, ConcreteEntityMetamodel->ChildAmbiguityException, ConcreteEntityMetamodel->EntityChildMetamodel, PolymorphicEntityMetamodelBuilder->EntityChildMetamodel, ConcreteEntityMetamodel$Builder->EntityChildMetamodel, EntityMetamodelBuilder->Enti..."
19,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.util,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,0.000000,2,2,"[GrpcExceptionParser->ErrorCode, ExceptionConverter->ErrorCode]","[AxonServerConnectionManager$Builder->GrpcMessageSizeInterceptor, ErrorCode->ExceptionConverter]"
20,axon-eventsourcing-5.0.1,org.axonframework.eventsourcing.annotation.reflection,axon-eventsourcing-5.0.1,org.axonframework.eventsourcing.annotation,0.000000,1,1,[AnnotationBasedEventSourcedEntityFactoryDefinition->EventSourcedEntityFactoryDefinition],[EventSourcedEntity->AnnotationBasedEventSourcedEntityFactoryDefinition]

### Table 2b - Cyclic Dependencies Break Down

Lists packages with cyclic dependencies with every dependency in a separate row sorted by the most promising  dependency first.

Only the top 40 entries are shown. The whole table can be found in the following CSV report:  
`Cyclic_Dependencies_Breakdown`

**Columns in addition to Table 2a:**
- *dependency* shows the cycle dependency in the text format "type1 -> type2" (forward) or "type2<-type1" (backward)

In [17]:
cyclic_dependencies_breakdown = query_cypher_to_data_frame("../cypher/Cyclic_Dependencies/Cyclic_Dependencies_Breakdown.cypher",limit=40)
cyclic_dependencies_breakdown

,artifactName,packageName,dependentArtifactName,dependentPackageName,dependency,forwardToBackwardBalance,numberForward,numberBackward
0,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,DefaultParameterResolverFactory$AnnotatedMetadataParameterResolver->Message,0.959184,48,1
1,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,AggregateTypeParameterResolverFactory$AggregateTypeParameterResolver->Context$ResourceKey,0.959184,48,1
2,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MethodInvokingMessageHandlingMember->MessageStream$Entry,0.959184,48,1
3,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,DefaultParameterResolverFactory$MessageParameterResolver->Message,0.959184,48,1
4,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,DefaultParameterResolverFactory$MetadataParameterResolver->Metadata,0.959184,48,1
5,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,AggregateTypeParameterResolverFactory$AggregateTypeParameterResolver->LegacyResources,0.959184,48,1
6,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MethodInvokingMessageHandlingMember->MessageStream$Single,0.959184,48,1
7,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MethodInvokingMessageHandlingMember->DelayedMessageStream,0.959184,48,1
8,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,AnnotatedMessageHandlingMemberDefinition->Message,0.959184,48,1
9,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,SourceIdParameterResolverFactory$SourceIdParameterResolver->Context$ResourceKey,0.959184,48,1
10,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MessageStreamResolverUtils->FluxUtils,0.959184,48,1
11,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,DefaultParameterResolverFactory$MetadataParameterResolver->Message,0.959184,48,1
12,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MessageStreamResolverUtils->MessageTypeResolver,0.959184,48,1
13,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MessageStreamResolverUtils->MonoUtils,0.959184,48,1
14,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MessageHandler->Message,0.959184,48,1
15,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MethodInvokingMessageHandlingMember->MessageStream,0.959184,48,1
16,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MethodInvokingMessageHandlingMember->Message,0.959184,48,1
17,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,AnnotationMessageTypeResolver->ClassBasedMessageTypeResolver,0.959184,48,1
18,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,ChainedMessageHandlerInterceptorMember->Message,0.959184,48,1
19,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,ChainedMessageHandlerInterceptorMember->MessageStream,0.959184,48,1
20,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,AnnotatedMessageHandlingMemberDefinition->MessageStream,0.959184,48,1
21,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,SourceIdParameterResolverFactory$SourceIdParameterResolver->LegacyResources,0.959184,48,1
22,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,HandlerAttributes<-SimpleHandlerAttributes,0.959184,48,1
23,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MessageStreamResolverUtils->MessageStream$Single,0.959184,48,1
24,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,InterceptorChainParameterResolverFactory->Context$ResourceKey,0.959184,48,1
25,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,DefaultParameterResolverFactory$AnnotatedMetadataParameterResolver->Metadata,0.959184,48,1
26,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MessageStreamResolverUtils->MessageStream$Empty,0.959184,48,1
27,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,HandlerDefinition->MessageStream,0.959184,48,1
28,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MessageStreamResolverUtils->GenericMessage,0.959184,48,1
29,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MessageStreamResolverUtils->MessageStream,0.959184,48,1
30,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,InterceptorChainParameterResolverFactory->MessageHandlerInterceptorChain,0.959184,48,1
31,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,DefaultParameterResolverFactory->Message,0.959184,48,1
32,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,InterceptorChainParameterResolverFactory->Message,0.959184,48,1
33,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,MethodInvokingMessageHandlingMember->MessageStream$Empty,0.959184,48,1
34,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,InterceptorChainParameterResolverFactory->MessageStream,0.959184,48,1
35,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,AnnotationMessageTypeResolver->MessageTypeResolver,0.959184,48,1
36,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,AnnotatedHandlerAttributes->SimpleHandlerAttributes,0.959184,48,1
37,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,AnnotationMessageTypeResolver->MessageType,0.959184,48,1
38,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,DefaultParameterResolverFactory->Metadata,0.959184,48,1
39,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,PayloadParameterResolver->Message,0.959184,48,1

### Table 2c - Cyclic Dependencies Break Down - Backward Dependencies Only

Lists packages with cyclic dependencies with every dependency in a separate row sorted by the most promising  dependency first. This table only contains the backward dependencies from the second participant of the cycle back to the first one that are the most promising to resolve.

Only the top 40 entries are shown. The whole table can be found in the following CSV report:  
`Cyclic_Dependencies_Breakdown_BackwardOnly`

In [18]:
cyclic_dependencies_breakdown_backward = query_cypher_to_data_frame("../cypher/Cyclic_Dependencies/Cyclic_Dependencies_Breakdown_Backward_Only.cypher",limit=40)
cyclic_dependencies_breakdown_backward

,artifactName,packageName,dependentArtifactName,dependentPackageName,dependency,forwardToBackwardBalance,numberForward,numberBackward
0,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core,HandlerAttributes<-SimpleHandlerAttributes,0.959184,48,1
1,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling,axon-messaging-5.0.1,org.axonframework.messaging.core,EventMessage<-SubscribableEventSource,0.942857,34,1
2,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,EventHandler<-HandlerTypeResolver,0.933333,29,1
3,axon-messaging-5.0.1,org.axonframework.messaging.commandhandling.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,CommandHandler<-HandlerTypeResolver,0.894737,18,1
4,axon-messaging-5.0.1,org.axonframework.messaging.queryhandling.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,QueryHandler<-HandlerTypeResolver,0.875000,15,1
5,axon-modelling-5.0.1,org.axonframework.modelling.annotation,axon-modelling-5.0.1,org.axonframework.modelling,TargetEntityIdMemberMismatchException<-PropertyBasedEntityIdResolver,0.846154,12,1
6,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.processing.streaming.pooled,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,PooledStreamingEventProcessorsConfigurer<-EventProcessingConfigurer,0.666667,15,3
7,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.processing.streaming.pooled,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,PooledStreamingEventProcessorModule<-EventProcessorModule,0.666667,15,3
8,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.processing.streaming.pooled,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,PooledStreamingEventProcessorConfiguration<-EventProcessorModule,0.666667,15,3
9,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.processing.subscribing,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,SubscribingEventProcessorConfiguration<-EventProcessorModule,0.666667,15,3
10,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.processing.subscribing,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,SubscribingEventProcessorModule<-EventProcessorModule,0.666667,15,3
11,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.processing.subscribing,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,SubscribingEventProcessorsConfigurer<-EventProcessingConfigurer,0.666667,15,3
12,axon-common-5.0.1,org.axonframework.common.configuration,axon-common-5.0.1,org.axonframework.common.infra,Component<-FilesystemStyleComponentDescriptor,0.529412,13,4
13,axon-common-5.0.1,org.axonframework.common.configuration,axon-common-5.0.1,org.axonframework.common.infra,Component$Identifier<-FilesystemStyleComponentDescriptor,0.529412,13,4
14,axon-common-5.0.1,org.axonframework.common.configuration,axon-common-5.0.1,org.axonframework.common.infra,Component$Identifier<-JacksonComponentDescriptor,0.529412,13,4
15,axon-common-5.0.1,org.axonframework.common.configuration,axon-common-5.0.1,org.axonframework.common.infra,Component<-JacksonComponentDescriptor,0.529412,13,4
16,axon-messaging-5.0.1,org.axonframework.messaging.core.interception.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,MessageHandlerInterceptorMemberChain<-AnnotatedHandlerInspector,0.500000,15,5
17,axon-messaging-5.0.1,org.axonframework.messaging.core.interception.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,MessageInterceptingMember<-AnnotatedHandlerInspector,0.500000,15,5
18,axon-messaging-5.0.1,org.axonframework.messaging.core.interception.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,NoMoreInterceptors<-ChainedMessageHandlerInterceptorMember,0.500000,15,5
19,axon-messaging-5.0.1,org.axonframework.messaging.core.interception.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,MessageHandlerInterceptorMemberChain<-ChainedMessageHandlerInterceptorMember,0.500000,15,5
20,axon-messaging-5.0.1,org.axonframework.messaging.core.interception.annotation,axon-messaging-5.0.1,org.axonframework.messaging.core.annotation,NoMoreInterceptors<-AnnotatedHandlerInspector,0.500000,15,5
21,axon-messaging-5.0.1,org.axonframework.messaging.core.unitofwork.transaction,axon-messaging-5.0.1,org.axonframework.messaging.core.unitofwork,TransactionManager<-TransactionalUnitOfWorkFactory,0.500000,6,2
22,axon-messaging-5.0.1,org.axonframework.messaging.core.unitofwork.transaction,axon-messaging-5.0.1,org.axonframework.messaging.core.unitofwork,Transaction<-TransactionalUnitOfWorkFactory,0.500000,6,2
23,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.event,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,AxonServerEventStorageEngineFactory<-AxonServerConfigurationEnhancer,0.428571,5,2
24,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.event,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,EventProcessorControlService<-AxonServerConfigurationEnhancer,0.428571,5,2
25,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.command,AxonServerConfiguration<-AxonServerCommandBusConnector,0.333333,4,2
26,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.command,MetadataConverter<-CommandConverter,0.333333,4,2
27,axon-messaging-5.0.1,org.axonframework.messaging.core.configuration,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.configuration,MessagingConfigurer<-EventProcessingConfigurer,0.333333,2,1
28,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.sequencing,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling,SequentialPolicy<-SimpleEventHandlingComponent,0.333333,8,4
29,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.sequencing,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling,HierarchicalSequencingPolicy<-SimpleEventHandlingComponent,0.333333,8,4
30,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.sequencing,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling,SequentialPerAggregatePolicy<-SimpleEventHandlingComponent,0.333333,8,4
31,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling.sequencing,axon-messaging-5.0.1,org.axonframework.messaging.eventhandling,SequencingPolicy<-SimpleEventHandlingComponent,0.333333,8,4
32,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.query,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,AxonServerQueryDispatchException<-ErrorCode,0.200000,6,4
33,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.query,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,AxonServerNonTransientRemoteQueryHandlingException<-ErrorCode,0.200000,6,4
34,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.query,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,AxonServerQueryBusConnector<-AxonServerConfigurationEnhancer,0.200000,6,4
35,axon-server-connector-5.0.1,org.axonframework.axonserver.connector.query,axon-server-connector-5.0.1,org.axonframework.axonserver.connector,AxonServerRemoteQueryHandlingException<-ErrorCode,0.200000,6,4
36,axon-modelling-5.0.1,org.axonframework.modelling.entity.annotation,axon-modelling-5.0.1,org.axonframework.modelling.annotation,AnnotatedEntityMetamodel<-EntityIdResolverDefinition,0.200000,3,2
37,axon-modelling-5.0.1,org.axonframework.modelling.entity.annotation,axon-modelling-5.0.1,org.axonframework.modelling.annotation,AnnotatedEntityMetamodel<-AnnotationBasedEntityIdResolverDefinition,0.200000,3,2
38,axon-messaging-5.0.1,org.axonframework.messaging.core.unitofwork,axon-messaging-5.0.1,org.axonframework.messaging.core,ProcessingContext<-MessageDispatchInterceptorChain,0.157895,11,8
39,axon-messaging-5.0.1,org.axonframework.messaging.core.unitofwork,axon-messaging-5.0.1,org.axonframework.messaging.core,ProcessingContext<-MessageDispatchInterceptor,0.157895,11,8

## Interface Segregation Candidates

Well known from [Design Principles and Design Patterns by Robert C. Martin](http://staff.cs.utu.fi/~jounsmed/doos_06/material/DesignPrinciplesAndPatterns.pdf), the *Interface Segregation Principle* suggests that software components should have narrow, focused interfaces rather than large, general-purpose ones. The goal is to minimize the dependencies between components and increase modularity, flexibility, and maintainability.

Smaller, focused and purpose-driven interfaces

- make it easier to modify individual components without affecting the rest of the system.
- make it clearer which client is affected by which change.
- don’t force their clients to depend on methods they don’t need.
- reduce the scope of changes since a change to one component doesn’t affect others.
- lead to a more loosely coupled architecture that is easier to understand and maintain.

Reference: [Analyze java package metrics in a graph database](https://joht.github.io/johtizen/data/2023/04/21/java-package-metrics-analysis.html#interface-segregation)

### How to apply the results

If just one method of a type is used, especially in many places, then the result of this method can be used to call e.g. a method or constuct an object instead of using the whole object and then just calling that single method.

If there are a couple of methods that are used for a distinct purpose, those could be factored out into a separate interface. The original type can extended/implement the new interface so that there are no breaking changes. Then all the callers, that use only this group of methods, can be changed to the new interface.

### Table 4 - Top 40 most used combinations of methods

The following table shows the top 40 most used combinations of methods of larger types that might benefit from applying the *Interface Segregation Principle*. The whole table can be found in the CSV report `Candidates_for_Interface_Segregation`.

In [19]:
interface_segregation_candidates=query_cypher_to_data_frame("../cypher/Internal_Dependencies/Candidates_for_Interface_Segregation.cypher", limit=40)
interface_segregation_candidates

,fullDependentTypeName,declaredMethods,calledMethodNames,calledMethods,callerTypes
0,org.axonframework.messaging.core.unitofwork.ProcessingContext,32,[computeResourceIfAbsent],1,7
1,org.axonframework.messaging.core.unitofwork.UnitOfWork,24,[executeWithResult],1,6
2,org.axonframework.common.configuration.ComponentDefinition$ComponentCreator,17,[createComponent],1,5
3,org.axonframework.messaging.commandhandling.CommandBus,6,[dispatch],1,5
4,org.axonframework.messaging.core.unitofwork.ProcessingContext,32,[withResource],1,4
5,org.axonframework.messaging.eventhandling.EventMessage,19,"[identifier, timestamp]",2,4
6,org.axonframework.messaging.eventhandling.EventMessage,19,[timestamp],1,4
7,org.axonframework.messaging.core.MessageStream$Entry,7,[message],1,4
8,org.axonframework.messaging.core.MessageStream$Empty,44,[cast],1,3
9,org.axonframework.messaging.core.DelayedMessageStream,42,[create],1,3
10,org.axonframework.messaging.core.unitofwork.UnitOfWork,24,[execute],1,3
11,org.axonframework.messaging.eventhandling.EventMessage,19,[identifier],1,3
12,org.axonframework.messaging.core.annotation.WrappedMessageHandlingMember,13,[handleSync],1,3
13,org.axonframework.messaging.core.unitofwork.ProcessingContext,32,[putResource],1,2
14,org.axonframework.messaging.core.unitofwork.UnitOfWork,25,[executeWithResult],1,2
15,org.axonframework.common.configuration.AbstractComponent,24,[describeTo],1,2
16,org.axonframework.messaging.commandhandling.CommandMessage,20,"[routingKey, priority]",2,2
17,org.axonframework.messaging.commandhandling.CommandMessage,19,[withConvertedPayload],1,2
18,org.axonframework.messaging.commandhandling.CommandMessage,19,[andMetadata],1,2
19,org.axonframework.messaging.eventhandling.EventMessage,19,[andMetadata],1,2
20,org.axonframework.messaging.eventhandling.EventMessage,19,[withConvertedPayload],1,2
21,org.axonframework.messaging.core.annotation.WrappedMessageHandlingMember,13,[canHandle],1,2
22,org.axonframework.messaging.eventstreaming.EventCriterion,12,[tags],1,2
23,org.axonframework.messaging.eventstreaming.OrEventCriteria,12,[or],1,2
24,org.axonframework.modelling.entity.PolymorphicEntityMetamodel,11,[forSuperType],1,2
25,org.axonframework.modelling.entity.annotation.AnnotatedEntityMetamodel,11,[entityType],1,2
26,org.axonframework.eventsourcing.eventstore.EventStore,9,[transaction],1,2
27,org.axonframework.messaging.eventhandling.EventHandlingComponent,8,"[sequenceIdentifierFor, supports, supportedEvents]",3,2
28,org.axonframework.messaging.eventhandling.processing.streaming.token.WrappedToken,8,[unwrapLowerBound],1,2
29,org.axonframework.messaging.eventhandling.processing.streaming.token.store.ConfigToken,8,[get],1,2
30,org.axonframework.messaging.core.MessageStream$Entry,7,[map],1,2
31,org.axonframework.messaging.core.EmptyMessageStream,44,[instance],1,1
32,org.axonframework.eventsourcing.eventstore.inmemory.InMemoryEventStorageEngine$MapBackedMessageStream,43,"[hasNextAvailable, isCompleted]",2,1
33,org.axonframework.eventsourcing.eventstore.inmemory.InMemoryEventStorageEngine$MapBackedMessageStream,42,[callback],1,1
34,org.axonframework.messaging.core.DelayedMessageStream,42,[createSingle],1,1
35,org.axonframework.messaging.core.MessageStream$Single,42,[cast],1,1
36,org.axonframework.messaging.core.MessageStream$Single,42,[asCompletableFuture],1,1
37,org.axonframework.messaging.core.MessageStream$Single,42,[first],1,1
38,org.axonframework.messaging.core.unitofwork.ProcessingContext,37,"[removeResource, updateResource, putResourceIfAbsent, putResource, computeResourceIfAbsent]",6,1
39,org.axonframework.messaging.core.unitofwork.ProcessingContext,36,"[updateResource, computeResourceIfAbsent]",2,1

## Package Usage

### Table 5 - Types that are used by multiple packages

This table shows the top 40 packages that are used by the highest number of different packages. The whole table can be found in the CSV report `List_types_that_are_used_by_many_different_packages`.

In [20]:
types_used_by_many_packages=query_cypher_to_data_frame("../cypher/Internal_Dependencies/List_types_that_are_used_by_many_different_packages.cypher", limit=40)
types_used_by_many_packages

,fullQualifiedDependentTypeName,dependentTypeName,dependentTypeLabels,numberOfUsingPackages
0,org.axonframework.messaging.core.unitofwork.ProcessingContext,ProcessingContext,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityBetweenness, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mar...",57
1,org.axonframework.common.annotation.Internal,Internal,"[Type, File, Java, ByteCode, Annotation, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent...",47
2,org.axonframework.messaging.core.Message,Message,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityBetweenness, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mar...",46
3,org.axonframework.common.infra.ComponentDescriptor,ComponentDescriptor,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0...",39
4,org.axonframework.messaging.eventhandling.EventMessage,EventMessage,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityBetweenness, Mark4TopCentralityHarmonic, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponen...",35
5,org.axonframework.messaging.core.MessageStream,MessageStream,"[Type, File, Java, ByteCode, Interface, GenericDeclaration, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityBetweenness, Mark4TopCentralityHarmonic, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWea...",35
6,org.axonframework.messaging.core.MessageType,MessageType,"[Type, File, Java, ByteCode, Record, Mark4TopCentralityBetweenness, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation3, M...",29
7,org.axonframework.messaging.core.QualifiedName,QualifiedName,"[Type, File, Java, ByteCode, Record, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityBetweenness, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4T...",29
8,org.axonframework.common.configuration.Configuration,Configuration,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation9, Mark4TypeLouvainCommunity0,...",28
9,org.axonframework.common.FutureUtils,FutureUtils,"[Type, File, Java, Class, ByteCode, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation14, Mark4TypeLouvainCommunity8, Mark...",26
10,org.axonframework.common.infra.DescribableComponent,DescribableComponent,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0...",24
11,org.axonframework.messaging.core.MessageStream$Empty,MessageStream$Empty,"[Type, File, Java, ByteCode, Interface, GenericDeclaration, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation26, Mark4TypeLouvainCommunity14, Mark4TypeLeidenCommunity13, Mark4Typ...",24
12,org.axonframework.messaging.core.Context$ResourceKey,Context$ResourceKey,"[Type, File, Java, Class, ByteCode, GenericDeclaration, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyCon...",23
13,org.axonframework.common.BuilderUtils,BuilderUtils,"[Type, File, Java, Class, ByteCode, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation2, Mark4TypeLouvainCommunity2, Mark4TypeLeidenCommunity2, Mark4TypeKCoreDecomposition8, Mark4TypeMaximumKCut47, Mark4TypeHDBSCAN31, Mark4TopAnomalyHub]",21
14,org.axonframework.common.configuration.ComponentRegistry,ComponentRegistry,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityBetweenness, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation17, Mark4TypeLouvainCommunity0, Mark4TypeLeidenCommunity0, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut0, Mark4TypeHDBSCAN77]",21
15,org.axonframework.common.Assert,Assert,"[Type, File, Java, Class, ByteCode, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation25, Mark4TypeLouvainCommunity13, Mark4TypeLeidenCommunity12, Mark4TypeKCoreDecompos...",20
16,org.axonframework.messaging.commandhandling.CommandMessage,CommandMessage,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityArticleRank, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation7, Mark4TypeLouvainCommunity10, Mark4TypeLeidenCommunity9,...",20
17,org.axonframework.messaging.core.MessageStream$Entry,MessageStream$Entry,"[Type, File, Java, ByteCode, Interface, GenericDeclaration, Mark4TopCentralityArticleRank, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation26, Mark4TypeLouvainCommunity14, Mark4...",19
18,org.axonframework.messaging.core.annotation.ParameterResolverFactory,ParameterResolverFactory,"[Type, File, Java, ByteCode, Interface, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation47, Mark4TypeLouvainCommunity1, Mark4TypeLeidenCommunity16, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut0, Mark4TypeHDBSCAN153]",19
19,org.axonframework.messaging.core.MessageStream$Single,MessageStream$Single,"[Type, File, Java, ByteCode, Interface, GenericDeclaration, Mark4TopCentralityArticleRank, Mark4TopCentralityBetweenness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation26, Mar...",18
20,org.axonframework.common.configuration.ConfigurationEnhancer,ConfigurationEnhancer,"[Type, File, Java, ByteCode, Interface, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation18, Mark4TypeLouvainCommunity0, Mark4TypeLeidenCommunity0, Mark4TypeKCoreDecomposition8, Mark4TypeMaximumKCut55, Mark4TypeHDBSCAN29]",17
21,org.axonframework.messaging.core.Metadata,Metadata,"[Type, File, Java, Class, ByteCode, Mark4TopCentralityPageRank, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation3, Mark4TypeLouvainCommunity3, Mark4TypeLeidenCommunity3, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut95, Ma...",16
22,org.axonframework.conversion.Converter,Converter,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation3, Mark4TypeLouvainCommunity3, Mark4TypeLeidenCommunity3, Mark4TypeKCoreDecompo...",15
23,org.axonframework.messaging.core.conversion.MessageConverter,MessageConverter,"[Type, File, Java, ByteCode, Interface, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation19, Mark4TypeLouvainCommunity3, Mark4TypeLeidenCommunity3, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut82, Mark4TypeLocalClusteringCoefficient0.1225296442687747, Mark4TypeHDBSCAN107]",15
24,org.axonframework.messaging.eventhandling.processing.streaming.token.TrackingToken,TrackingToken,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityArticleRank, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation23, Mark4TypeLouvainCommunity8, Mark4TypeLeidenCommunity11...",15
25,org.axonframework.common.AxonConfigurationException,AxonConfigurationException,"[Type, File, Java, Class, ByteCode, Throwable, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation1, Mark4TypeLouvainCommunity1, Mark4TypeLeidenCommunity1, Mark4TypeKCoreDecomposition8, Mark4TypeMaximumKCut0, Mark4TypeHDBSCAN-1]",14
26,org.axonframework.messaging.core.MessageTypeResolver,MessageTypeResolver,"[Type, File, Java, ByteCode, Interface, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation3, Mark4TypeLouvainCommunity3, Mark4TypeLeidenCommunity3, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut67, Mark4TypeHDBSCAN-1]",14
27,org.axonframework.common.ObjectUtils,ObjectUtils,"[Type, File, Java, Class, ByteCode, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation3, Mark4TypeLouvainCommunity3, Mark4TypeLeidenCommunity3, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut6, Mark4TypeHDBSCAN5]",14
28,org.axonframework.messaging.commandhandling.CommandBus,CommandBus,"[Type, File, Java, ByteCode, Interface, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation26, Mark4TypeLouvainCommunity10, Mark4TypeLeidenCommunity9, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut0, Mark4TypeHDBSCAN57]",13
29,org.axonframework.messaging.queryhandling.QueryMessage,QueryMessage,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation12, Mark4TypeLouvainCommunity9, Mark4TypeLeidenCommunity8, Mark4TypeKCoreDecomposition9, ...",13
30,org.axonframework.messaging.commandhandling.CommandResultMessage,CommandResultMessage,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation3, Mark4TypeLouvainCommunity3, Mark4TypeLeidenCommunity3, Mark4TypeKCoreDecomposition9, M...",12
31,org.axonframework.common.configuration.ComponentDefinition,ComponentDefinition,"[Type, File, Java, ByteCode, Interface, GenericDeclaration, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation5, Mark4TypeLouvainCommunity0, Mark4TypeLeidenCommunity0, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut4, Mark4TypeLocalClusteringCoefficient0.2028985507246377, Mark4Type...",12
32,org.axonframework.common.configuration.ComponentDefinition$IncompleteComponentDefinition,ComponentDefinition$IncompleteComponentDefinition,"[Type, File, Java, ByteCode, Interface, GenericDeclaration, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation5, Mark4TypeLouvainCommunity0, Mark4TypeLeidenCommunity0, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut81, Mark4TypeHDBSCAN29]",12
33,org.axonframework.messaging.core.Context,Context,"[Type, File, Java, ByteCode, Interface, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityBetweenness, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation26, Mark4TypeLouvainCommunity14, Mark4TypeLeiden...",12
34,org.axonframework.common.ReflectionUtils,ReflectionUtils,"[Type, File, Java, Class, ByteCode, Mark4TopCentralityBetweenness, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation25, Mark4TypeLouvainCommunity1, Mark4TypeLeidenCommunity14, Mark4TypeKCoreDecomposition8, Mark4TypeMaximumKCut99, Mark4TypeHDBSCAN-1, Mark4TopAnomalyBottleneck]",12
35,org.axonframework.common.AxonNonTransientException,AxonNonTransientException,"[Type, File, Java, Class, ByteCode, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation10, Mark4TypeLouvainCommunity7, Mark4TypeLeidenCommunity7, Mark4TypeKCoreDecomposition4, Mark4TypeMaximumKCut86, Mark4TypeLocalClusteringCoe...",11
36,org.axonframework.common.configuration.ComponentBuilder,ComponentBuilder,"[Type, File, Java, ByteCode, Interface, GenericDeclaration, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation17, Mark4TypeLouvainCommunity0, Mark4TypeLeidenCommunity0, Mark4TypeKCoreDecomposition9, Mark4TypeMaximumKCut1, Mark4TypeHDBSCAN-1]",11
37,org.axonframework.messaging.core.MessageHandlerInterceptor,MessageHandlerInterceptor,"[Type, File, Java, ByteCode, Interface, GenericDeclaration, Mark4TopCentralityBetweenness, Mark4TopCentralityHyperlinkInducedTopicSearchAuthority, Mark4TopCentralityHyperlinkInducedTopicSearchHub, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation52, Mark4TypeLouvainCommunity0, Mark4T...",11
38,org.axonframework.messaging.core.annotation.ParameterResolver,ParameterResolver,"[Type, File, Java, ByteCode, Interface, GenericDeclaration, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation14, Mark4TypeLouvainCommunity1, Mark4TypeLeidenCommunity1, Mark4TypeKCoreDecomposition7, Mark4TypeMaximumKCut51, Mark4TypeHDBSCAN169]",11
39,org.axonframework.common.TypeReference,TypeReference,"[Type, File, Java, Class, ByteCode, GenericDeclaration, Mark4TopCentralityPageRank, Mark4TopCentralityArticleRank, Mark4TopCentralityBetweenness, Mark4TopCentralityHarmonic, Mark4TopCentralityCloseness, Mark4TypeWeaklyConnectedComponent0, Mark4TypeLabelPropagation3, Mark4TypeLouvainCommunity0, M...",11

### Table 6 - Packages that are used by multiple artifacts

This table shows the top 30 artifacts that only use a few (compared to all existing) packages of another artifact.
The whole table can be found in the CSV report `ArtifactPackageUsage`.

In [21]:
used_packages_of_dependent_artifact=query_cypher_to_data_frame("../cypher/Internal_Dependencies/How_many_packages_compared_to_all_existing_are_used_by_dependent_artifacts.cypher",limit=30)
used_packages_of_dependent_artifact

,artifactName,dependentArtifactName,dependentPackages,dependentArtifactPackages,packageUsagePercentage,dependentFullQualifiedPackageNames,dependentPackageNames
0,axon-tracing-opentelemetry-5.0.1,axon-messaging-5.0.1,2,57,0.035088,"[org.axonframework.messaging.tracing, org.axonframework.messaging.core]","[tracing, core]"
1,axon-tracing-opentelemetry-5.0.1,axon-common-5.0.1,1,13,0.076923,[org.axonframework.common],[common]
2,axon-metrics-micrometer-5.0.1,axon-messaging-5.0.1,6,57,0.105263,"[org.axonframework.messaging.queryhandling, org.axonframework.messaging.monitoring, org.axonframework.messaging.core, org.axonframework.messaging.eventhandling, org.axonframework.messaging.eventhandling.processing, org.axonframework.messaging.commandhandling]","[queryhandling, monitoring, core, eventhandling, processing, commandhandling]"
3,axon-test-5.0.1,axon-messaging-5.0.1,8,57,0.140351,"[org.axonframework.messaging.commandhandling, org.axonframework.messaging.core, org.axonframework.messaging.monitoring, org.axonframework.messaging.core.unitofwork, org.axonframework.messaging.eventhandling.processing.streaming.token, org.axonframework.messaging.eventstreaming, org.axonframework...","[commandhandling, core, monitoring, unitofwork, token, eventstreaming, eventhandling, annotation]"
4,axon-server-connector-5.0.1,axon-modelling-5.0.1,1,7,0.142857,[org.axonframework.modelling],[modelling]
5,axon-server-connector-5.0.1,axon-eventsourcing-5.0.1,1,7,0.142857,[org.axonframework.eventsourcing.eventstore],[eventstore]
6,axon-test-5.0.1,axon-eventsourcing-5.0.1,1,7,0.142857,[org.axonframework.eventsourcing.eventstore],[eventstore]
7,axon-metrics-micrometer-5.0.1,axon-common-5.0.1,2,13,0.153846,"[org.axonframework.common.configuration, org.axonframework.common]","[configuration, common]"
8,axon-spring-boot-autoconfigure-5.0.1,axon-server-connector-5.0.1,1,5,0.200000,[org.axonframework.axonserver.connector],[connector]
9,axon-spring-boot-autoconfigure-5.0.1,axon-test-5.0.1,1,5,0.200000,[org.axonframework.test.server],[server]
10,axon-modelling-5.0.1,axon-messaging-5.0.1,13,57,0.228070,"[org.axonframework.messaging.core.unitofwork, org.axonframework.messaging.eventhandling, org.axonframework.messaging.core, org.axonframework.messaging.commandhandling, org.axonframework.messaging.core.annotation, org.axonframework.messaging.eventhandling.conversion, org.axonframework.messaging.c...","[unitofwork, eventhandling, core, commandhandling, annotation, conversion, reflection, configuration]"
11,axon-update-5.0.1,axon-common-5.0.1,3,13,0.230769,"[org.axonframework.common.annotation, org.axonframework.common, org.axonframework.common.configuration]","[annotation, common, configuration]"
12,axon-conversion-5.0.1,axon-common-5.0.1,3,13,0.230769,"[org.axonframework.common.annotation, org.axonframework.common.infra, org.axonframework.common]","[annotation, infra, common]"
13,axon-conversion-5.0.1,axon-conversion-5.0.1,1,4,0.250000,[org.axonframework.conversion],[conversion]
14,axon-modelling-5.0.1,axon-conversion-5.0.1,1,4,0.250000,[org.axonframework.conversion],[conversion]
15,axon-eventsourcing-5.0.1,axon-conversion-5.0.1,1,4,0.250000,[org.axonframework.conversion],[conversion]
16,axon-spring-boot-autoconfigure-5.0.1,axon-messaging-5.0.1,15,57,0.263158,"[org.axonframework.messaging.core.timeout, org.axonframework.messaging.core, org.axonframework.messaging.core.correlation, org.axonframework.messaging.commandhandling.distributed, org.axonframework.messaging.eventhandling, org.axonframework.messaging.core.annotation, org.axonframework.messaging....","[timeout, core, correlation, distributed, eventhandling, annotation, store, commandhandling, conversion, queryhandling, jpa, transaction, interception]"
17,axon-eventsourcing-5.0.1,axon-messaging-5.0.1,16,57,0.280702,"[org.axonframework.messaging.eventhandling.annotation, org.axonframework.messaging.eventstreaming, org.axonframework.messaging.core.unitofwork, org.axonframework.messaging.eventhandling, org.axonframework.messaging.core, org.axonframework.messaging.eventhandling.processing.streaming.token, org.a...","[annotation, eventstreaming, unitofwork, eventhandling, core, token, conversion, configuration, interception, commandhandling, transaction]"
18,axon-server-connector-5.0.1,axon-messaging-5.0.1,16,57,0.280702,"[org.axonframework.messaging.queryhandling, org.axonframework.messaging.core.unitofwork, org.axonframework.messaging.core, org.axonframework.messaging.queryhandling.distributed, org.axonframework.messaging.eventhandling.processing.streaming.token, org.axonframework.messaging.eventhandling.proces...","[queryhandling, unitofwork, core, distributed, token, streaming, conversion, segmenting, processing, eventstreaming, eventhandling, subscribing, store, commandhandling]"
19,axon-spring-boot-autoconfigure-5.0.1,axon-eventsourcing-5.0.1,2,7,0.285714,"[org.axonframework.eventsourcing.eventstore, org.axonframework.eventsourcing.eventstore.jpa]","[eventstore, jpa]"
20,axon-test-5.0.1,axon-common-5.0.1,4,13,0.307692,"[org.axonframework.common, org.axonframework.common.infra, org.axonframework.common.annotation, org.axonframework.common.configuration]","[common, infra, annotation, configuration]"
21,axon-spring-boot-autoconfigure-5.0.1,axon-common-5.0.1,4,13,0.307692,"[org.axonframework.common.jpa, org.axonframework.common, org.axonframework.common.configuration, org.axonframework.common.jdbc]","[jpa, common, configuration, jdbc]"
22,axon-modelling-5.0.1,axon-common-5.0.1,5,13,0.384615,"[org.axonframework.common.infra, org.axonframework.common.configuration, org.axonframework.common.annotation, org.axonframework.common, org.axonframework.common.property]","[infra, configuration, annotation, common, property]"
23,axon-common-5.0.1,axon-common-5.0.1,6,13,0.461538,"[org.axonframework.common, org.axonframework.common.io, org.axonframework.common.configuration, org.axonframework.common.annotation, org.axonframework.common.lifecycle, org.axonframework.common.infra]","[common, io, configuration, annotation, lifecycle, infra]"
24,axon-server-connector-5.0.1,axon-common-5.0.1,6,13,0.461538,"[org.axonframework.common, org.axonframework.common.util, org.axonframework.common.infra, org.axonframework.common.lifecycle, org.axonframework.common.annotation, org.axonframework.common.configuration]","[common, util, infra, lifecycle, annotation, configuration]"
25,axon-messaging-5.0.1,axon-conversion-5.0.1,2,4,0.500000,"[org.axonframework.conversion.json, org.axonframework.conversion]","[json, conversion]"
26,axon-metrics-micrometer-5.0.1,axon-metrics-micrometer-5.0.1,1,2,0.500000,[org.axonframework.extension.metrics.micrometer.reservoir],[reservoir]
27,axon-eventsourcing-5.0.1,axon-common-5.0.1,7,13,0.538462,"[org.axonframework.common.annotation, org.axonframework.common, org.axonframework.common.infra, org.axonframework.common.configuration, org.axonframework.common.jdbc, org.axonframework.common.jpa, org.axonframework.common.io]","[annotation, common, infra, configuration, jdbc, jpa, io]"
28,axon-spring-boot-autoconfigure-5.0.1,axon-update-5.0.1,3,5,0.600000,"[org.axonframework.update.configuration, org.axonframework.update, org.axonframework.update.detection]","[configuration, update, detection]"
29,axon-test-5.0.1,axon-test-5.0.1,3,5,0.600000,"[org.axonframework.test.matchers, org.axonframework.test.util, org.axonframework.test]","[matchers, util, test]"

### Table 7 - Types that are used by multiple artifacts

This table shows the top 30 types that only use a few (compared to all existing) types of another artifact. The whole table can be found in the CSV report `ClassesPerPackageUsageAcrossArtifacts`.

In [22]:
used_types_of_dependent_artifact=query_cypher_to_data_frame("../cypher/Internal_Dependencies/How_many_classes_compared_to_all_existing_in_the_same_package_are_used_by_dependent_packages_across_different_artifacts.cypher", limit=30)
used_types_of_dependent_artifact

,artifactName,dependentArtifactName,packageName,dependentPackage.fqn,dependentTypes,dependentPackageTypes,typeUsagePercentage,dependentTypeNames
0,axon-eventsourcing-5.0.1,axon-messaging-5.0.1,org.axonframework.eventsourcing.configuration,org.axonframework.messaging.core,1,80,0.012500,[org.axonframework.messaging.core.MessageTypeResolver]
1,axon-test-5.0.1,axon-messaging-5.0.1,org.axonframework.test.matchers,org.axonframework.messaging.core,1,80,0.012500,[org.axonframework.messaging.core.Message]
2,axon-modelling-5.0.1,axon-messaging-5.0.1,org.axonframework.modelling.repository,org.axonframework.messaging.core,1,80,0.012500,[org.axonframework.messaging.core.Context$ResourceKey]
3,axon-eventsourcing-5.0.1,axon-messaging-5.0.1,org.axonframework.eventsourcing.configuration,org.axonframework.messaging.core.annotation,1,50,0.020000,[org.axonframework.messaging.core.annotation.ParameterResolverFactory]
4,axon-spring-boot-autoconfigure-5.0.1,axon-messaging-5.0.1,org.axonframework.extension.springboot.autoconfig,org.axonframework.messaging.core.annotation,1,50,0.020000,[org.axonframework.messaging.core.annotation.HandlerEnhancerDefinition]
5,axon-modelling-5.0.1,axon-common-5.0.1,org.axonframework.modelling.entity.annotation,org.axonframework.common.configuration,1,46,0.021739,[org.axonframework.common.configuration.Configuration]
6,axon-eventsourcing-5.0.1,axon-common-5.0.1,org.axonframework.eventsourcing.annotation,org.axonframework.common.configuration,1,46,0.021739,[org.axonframework.common.configuration.Configuration]
7,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.core,org.axonframework.common.configuration,1,46,0.021739,[org.axonframework.common.configuration.Configuration]
8,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.core.unitofwork,org.axonframework.common.configuration,1,46,0.021739,[org.axonframework.common.configuration.ComponentNotFoundException]
9,axon-eventsourcing-5.0.1,axon-common-5.0.1,org.axonframework.eventsourcing.annotation.reflection,org.axonframework.common.configuration,1,46,0.021739,[org.axonframework.common.configuration.Configuration]
10,axon-metrics-micrometer-5.0.1,axon-messaging-5.0.1,org.axonframework.extension.metrics.micrometer,org.axonframework.messaging.core,2,80,0.025000,"[org.axonframework.messaging.core.Metadata, org.axonframework.messaging.core.Message]"
11,axon-tracing-opentelemetry-5.0.1,axon-messaging-5.0.1,org.axonframework.extension.tracing.opentelemetry,org.axonframework.messaging.core,2,80,0.025000,"[org.axonframework.messaging.core.Metadata, org.axonframework.messaging.core.Message]"
12,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.core.timeout,org.axonframework.common,1,34,0.029412,[org.axonframework.common.AxonThreadFactory]
13,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.eventhandling.processing.streaming.token.store,org.axonframework.common,1,34,0.029412,[org.axonframework.common.AxonTransientException]
14,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.eventstreaming,org.axonframework.common,1,34,0.029412,[org.axonframework.common.Assert]
15,axon-spring-boot-autoconfigure-5.0.1,axon-common-5.0.1,org.axonframework.extension.springboot.autoconfig,org.axonframework.common,1,34,0.029412,[org.axonframework.common.AxonConfigurationException]
16,axon-test-5.0.1,axon-common-5.0.1,org.axonframework.test.server,org.axonframework.common,1,34,0.029412,[org.axonframework.common.Assert]
17,axon-conversion-5.0.1,axon-common-5.0.1,org.axonframework.conversion.avro,org.axonframework.common,1,34,0.029412,[org.axonframework.common.BuilderUtils]
18,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.queryhandling.configuration,org.axonframework.common,1,34,0.029412,[org.axonframework.common.FutureUtils]
19,axon-modelling-5.0.1,axon-common-5.0.1,org.axonframework.modelling.repository,org.axonframework.common,1,34,0.029412,[org.axonframework.common.FutureUtils]
20,axon-update-5.0.1,axon-common-5.0.1,org.axonframework.update,org.axonframework.common,1,34,0.029412,[org.axonframework.common.ObjectUtils]
21,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.commandhandling.retry,org.axonframework.common,1,34,0.029412,[org.axonframework.common.FutureUtils]
22,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.eventhandling.processing,org.axonframework.common,1,34,0.029412,[org.axonframework.common.AxonException]
23,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.core.configuration.reflection,org.axonframework.common,1,34,0.029412,[org.axonframework.common.Priority]
24,axon-test-5.0.1,axon-common-5.0.1,org.axonframework.test.fixture,org.axonframework.common,1,34,0.029412,[org.axonframework.common.Registration]
25,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.core.interception.annotation,org.axonframework.common,1,34,0.029412,[org.axonframework.common.AxonConfigurationException]
26,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.queryhandling.annotation,org.axonframework.common,1,34,0.029412,[org.axonframework.common.ReflectionUtils]
27,axon-test-5.0.1,axon-common-5.0.1,org.axonframework.test.util,org.axonframework.common,1,34,0.029412,[org.axonframework.common.ObjectUtils]
28,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.monitoring.configuration,org.axonframework.common,1,34,0.029412,[org.axonframework.common.TypeReference]
29,axon-messaging-5.0.1,axon-common-5.0.1,org.axonframework.messaging.commandhandling.configuration,org.axonframework.common,1,34,0.029412,[org.axonframework.common.FutureUtils]

### Table 8 - Duplicate package names across artifacts

This table shows the top 30 duplicate package names across artifacts. They are ordered by the number of duplicates descending.

This might lead to confusion, makes importing more error prone and might even lead to duplicate classes where only one of them will be loaded by the class loader. If a package is named the same way in two or more artifacts this even allows another artifact to access package protected classes, methods or members which might not be intended. 

The whole table can be found in the CSV report `DuplicatePackageNamesAcrossArtifacts`.

In [23]:
duplicate_package_names_across_artifacts=query_cypher_to_data_frame("../cypher/Artifact_Dependencies/Artifacts_with_duplicate_packages.cypher", limit=30)
duplicate_package_names_across_artifacts

Empty DataFrame
Columns: [packageName, duplicates, artifactNames]
Index: []

### Table 9 - Annotated elements

This table shows 30 most used Java Annotations including some examples where they are used.

In [24]:
annotated_elements=query_cypher_to_data_frame("../cypher/Java/Annotated_code_elements.cypher", limit=30)
annotated_elements

,annotationName,languageElement,numberOfAnnotatedElements,examples
0,jakarta.annotation.Nonnull,Parameter,3382,"[org.axonframework.axonserver.connector.MetadataConverter.convertGrpcToMetadataValues(0), org.axonframework.axonserver.connector.MetadataConverter.convertMetadataValuesToGrpc(0), org.axonframework.axonserver.connector.util.PriorityExecutorService.awaitTermination(1), org.axonframework.axonserver..."
1,jakarta.annotation.Nonnull,Method,833,"[org.axonframework.axonserver.connector.MetadataConverter.convertGrpcToMetadataValues, org.axonframework.axonserver.connector.MetadataConverter.convertMetadataValuesToGrpc, org.axonframework.axonserver.connector.util.PriorityExecutorService.shutdownNow, org.axonframework.axonserver.connector.uti..."
2,jakarta.annotation.Nullable,Parameter,399,"[org.axonframework.axonserver.connector.util.ExceptionConverter.convertToErrorMessage(1), org.axonframework.axonserver.connector.query.AxonServerQueryBusConnector.query(1), org.axonframework.axonserver.connector.query.AxonServerQueryBusConnector.subscriptionQuery(1), org.axonframework.axonserver..."
3,jakarta.annotation.Nullable,Method,99,"[org.axonframework.test.fixture.RecordingCommandBus.resultOf, org.axonframework.modelling.annotation.InjectEntityParameterResolverFactory.createInstance, org.axonframework.modelling.entity.annotation.AnnotatedEntityMetamodel.getExpectedRepresentation, org.axonframework.modelling.entity.child.Com..."
4,org.axonframework.common.annotation.Internal,Class,75,"[org.axonframework.axonserver.connector.MetadataConverter, org.axonframework.axonserver.connector.query.AbstractQueryResponseMessageStream, org.axonframework.axonserver.connector.query.QueryConverter, org.axonframework.axonserver.connector.query.QueryResponseMessageStream, org.axonframework.axon..."
5,jakarta.annotation.Nonnull,Field,70,"[org.axonframework.axonserver.connector.command.AxonServerCommandBusConnector$FutureResultCallback.result, org.axonframework.axonserver.connector.command.AxonServerCommandBusConnector$FutureResultCallback.command, org.axonframework.test.fixture.AxonTestFixture$Customization.fieldFilters, org.axo..."
6,java.lang.FunctionalInterface,Interface,55,"[org.axonframework.axonserver.connector.ErrorCode$ExceptionBuilder, org.axonframework.axonserver.connector.ManagedChannelCustomizer, org.axonframework.axonserver.connector.InstructionAckSource, org.axonframework.axonserver.connector.TargetContextResolver, org.axonframework.axonserver.connector.T..."
7,java.lang.annotation.Retention,Annotation,42,"[org.axonframework.extension.springboot.util.RegisterDefaultEntities, org.axonframework.extension.springboot.util.ConditionalOnQualifiedBean, org.axonframework.extension.springboot.util.ConditionalOnMissingQualifiedBean, org.axonframework.modelling.annotation.TargetEntityId, org.axonframework.mo..."
8,java.lang.annotation.Target,Annotation,42,"[org.axonframework.extension.springboot.util.RegisterDefaultEntities, org.axonframework.extension.springboot.util.ConditionalOnQualifiedBean, org.axonframework.extension.springboot.util.ConditionalOnMissingQualifiedBean, org.axonframework.modelling.annotation.TargetEntityId, org.axonframework.mo..."
9,org.springframework.context.annotation.Bean,Method,36,"[org.axonframework.extension.springboot.autoconfig.AxonTimeoutAutoConfiguration.messageTimeoutHandlerEnhancerDefinition, org.axonframework.extension.springboot.autoconfig.AxonTimeoutAutoConfiguration.axonTimeoutConfigurationEnhancer, org.axonframework.extension.springboot.autoconfig.AvroSchemaSt..."
10,org.axonframework.common.annotation.Internal,Constructor,19,"[org.axonframework.messaging.eventhandling.processing.streaming.pooled.PooledStreamingEventProcessorConfiguration.<init>, org.axonframework.messaging.eventhandling.processing.streaming.pooled.PooledStreamingEventProcessorsConfigurer.<init>, org.axonframework.messaging.eventhandling.processing.su..."
11,org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean,Method,18,"[org.axonframework.extension.springboot.autoconfig.JpaAutoConfiguration.entityManagerProvider, org.axonframework.extension.springboot.autoconfig.JpaAutoConfiguration.tokenStore, org.axonframework.extension.springboot.autoconfig.JpaAutoConfiguration.persistenceExceptionResolver, org.axonframework..."
12,org.springframework.boot.autoconfigure.AutoConfiguration,Class,18,"[org.axonframework.extension.springboot.autoconfig.AxonTimeoutAutoConfiguration, org.axonframework.extension.springboot.autoconfig.CorrelationDataProviderAutoConfiguration, org.axonframework.extension.springboot.autoconfig.AvroSchemaStoreAutoConfiguration, org.axonframework.extension.springboot...."
13,java.lang.annotation.Documented,Annotation,15,"[org.axonframework.extension.springboot.util.ConditionalOnQualifiedBean, org.axonframework.extension.springboot.util.ConditionalOnMissingQualifiedBean, org.axonframework.modelling.entity.annotation.EntityMember, org.axonframework.messaging.commandhandling.annotation.CommandHandler, org.axonframe..."
14,org.axonframework.common.annotation.Internal,Interface,14,"[org.axonframework.modelling.entity.annotation.AnnotatedEntityMetamodelFactory, org.axonframework.messaging.commandhandling.annotation.CommandHandlingMember, org.axonframework.messaging.eventhandling.annotation.EventHandlingMember, org.axonframework.messaging.queryhandling.annotation.QueryHandli..."
15,com.fasterxml.jackson.annotation.JsonProperty,Parameter,12,"[org.axonframework.messaging.eventhandling.processing.streaming.token.GapAwareTrackingToken.<init>(0), org.axonframework.messaging.eventhandling.processing.streaming.token.GapAwareTrackingToken.<init>(1), org.axonframework.messaging.eventhandling.processing.streaming.token.store.ConfigToken.<ini..."
16,org.axonframework.common.Priority,Class,12,"[org.axonframework.test.FixtureResourceParameterResolverFactory, org.axonframework.messaging.eventhandling.annotation.SequenceNumberParameterResolverFactory, org.axonframework.messaging.eventhandling.annotation.TimestampParameterResolverFactory, org.axonframework.messaging.core.annotation.Hierar..."
17,org.springframework.boot.context.properties.ConfigurationProperties,Class,10,"[org.axonframework.axonserver.connector.AxonServerConfiguration, org.axonframework.extension.springboot.DistributedCommandBusProperties, org.axonframework.extension.springboot.TokenStoreProperties, org.axonframework.extension.springboot.TagsConfigurationProperties, org.axonframework.extension.sp..."
18,org.axonframework.common.annotation.Internal,Method,10,"[org.axonframework.messaging.eventhandling.conversion.DelegatingEventConverter.delegate, org.axonframework.messaging.eventhandling.processing.streaming.token.store.jdbc.JdbcTokenStore.converter, org.axonframework.messaging.eventhandling.processing.streaming.token.store.jpa.JpaTokenStore.converte..."
19,org.springframework.boot.context.properties.EnableConfigurationProperties,Class,9,"[org.axonframework.extension.springboot.autoconfig.AxonTimeoutAutoConfiguration, org.axonframework.extension.springboot.autoconfig.JpaAutoConfiguration, org.axonframework.extension.springboot.autoconfig.AxonServerAutoConfiguration, org.axonframework.extension.springboot.autoconfig.JpaEventStoreA..."
20,jakarta.persistence.Basic,Field,8,"[org.axonframework.messaging.eventhandling.processing.streaming.token.store.jpa.TokenEntry.tokenType, org.axonframework.messaging.eventhandling.processing.streaming.token.store.jpa.TokenEntry.timestamp, org.axonframework.messaging.eventhandling.processing.streaming.token.store.jpa.TokenEntry.own..."
21,org.springframework.boot.context.properties.NestedConfigurationProperty,Field,8,"[org.axonframework.extension.springboot.TimeoutProperties$MessageHandlerTimeoutProperties.events, org.axonframework.extension.springboot.TimeoutProperties$MessageHandlerTimeoutProperties.commands, org.axonframework.extension.springboot.TimeoutProperties$MessageHandlerTimeoutProperties.queries, o..."
22,org.springframework.boot.autoconfigure.condition.ConditionalOnProperty,Class,8,"[org.axonframework.extension.springboot.autoconfig.AxonTimeoutAutoConfiguration, org.axonframework.extension.springboot.autoconfig.AvroSchemaStoreAutoConfiguration$AvroConfiguredCondition$MessagesAvroCondition, org.axonframework.extension.springboot.autoconfig.AvroSchemaStoreAutoConfiguration$Av..."
23,java.lang.SafeVarargs,Constructor,7,"[org.axonframework.test.matchers.SequenceMatcher.<init>, org.axonframework.test.matchers.ListMatcher.<init>, org.axonframework.test.matchers.ExactSequenceMatcher.<init>, org.axonframework.test.matchers.ListWithAllOfMatcher.<init>, org.axonframework.test.matchers.ListWithAnyOfMatcher.<init>, org...."
24,org.springframework.boot.autoconfigure.condition.ConditionalOnClass,Class,7,"[org.axonframework.extension.springboot.autoconfig.AvroSchemaStoreAutoConfiguration, org.axonframework.extension.springboot.autoconfig.JpaAutoConfiguration, org.axonframework.extension.springboot.autoconfig.AxonServerAutoConfiguration, org.axonframework.extension.springboot.autoconfig.ObjectMapp..."
25,java.beans.ConstructorProperties,Constructor,6,"[org.axonframework.messaging.eventhandling.processing.streaming.token.GapAwareTrackingToken.<init>, org.axonframework.messaging.eventhandling.processing.streaming.token.store.ConfigToken.<init>, org.axonframework.messaging.eventhandling.processing.streaming.token.ReplayToken.<init>, org.axonfram..."
26,org.springframework.boot.context.properties.bind.DefaultValue,Parameter,6,"[org.axonframework.extension.springboot.JpaEventStorageEngineConfigurationProperties.<init>(0), org.axonframework.extension.springboot.JpaEventStorageEngineConfigurationProperties.<init>(1), org.axonframework.extension.springboot.JpaEventStorageEngineConfigurationProperties.<init>(2), org.axonfr..."
27,org.springframework.context.annotation.Conditional,Method,6,"[org.axonframework.extension.springboot.autoconfig.AvroSchemaStoreAutoConfiguration.defaultAxonSchemaStore, org.axonframework.extension.springboot.autoconfig.AvroSchemaStoreAutoConfiguration.collectAvroSchemasFromClassPath, org.axonframework.extension.springboot.autoconfig.AvroSchemaStoreAutoCon..."
28,com.fasterxml.jackson.annotation.JsonCreator,Constructor,6,"[org.axonframework.messaging.eventhandling.processing.streaming.token.GapAwareTrackingToken.<init>, org.axonframework.messaging.eventhandling.processing.streaming.token.store.ConfigToken.<init>, org.axonframework.messaging.eventhandling.processing.streaming.token.ReplayToken.<init>, org.axonfram..."
29,org.springframework.boot.autoconfigure.AutoConfigureBefore,Class,6,"[org.axonframework.extension.springboot.autoconfig.CorrelationDataProviderAutoConfiguration, org.axonframework.extension.springboot.autoconfig.AvroSchemaStoreAutoConfiguration, org.axonframework.extension.springboot.autoconfig.AxonServerAutoConfiguration, org.axonframework.extension.springboot.a..."

### Table 10 - Distance distribution between dependent files

This table shows the file directory distance distribution between dependent files. Intuitively, the distance is given by the fewest number of change directory commands needed to navigate between a file and a dependency it uses. Those are aggregate to see how many dependent files are in the same directory, how many are just one change directory command apart, and so on.

In [25]:
query_first_non_empty_cypher_to_data_frame("../cypher/Internal_Dependencies/Get_file_distance_as_shortest_contains_path_for_dependencies.cypher",
                                           "../cypher/Internal_Dependencies/Set_file_distance_as_shortest_contains_path_for_dependencies.cypher", limit=20)

,dependency.fileDistanceAsFewestChangeDirectoryCommands,numberOfDependencies,numberOfDependencyUsers,numberOfDependencyProviders,examples
0,0,2080,854,896,"[/axon-spring-boot-autoconfigure-5.0.1.jar uses /axon-server-connector-5.0.1.jar, /org/axonframework/axonserver/connector/command uses /org/axonframework/axonserver/connector/util, /org/axonframework/axonserver/connector/query uses /org/axonframework/axonserver/connector/util, /org/axonframework..."
1,1,96,82,41,"[/org/axonframework/axonserver/connector/query uses /org/axonframework/axonserver/connector, /org/axonframework/axonserver/connector/command uses /org/axonframework/axonserver/connector, /org/axonframework/axonserver/connector/util uses /org/axonframework/axonserver/connector, /org/axonframework..."
2,2,2067,606,417,"[/org/axonframework/axonserver/connector/command/CommandConverter.class uses /org/axonframework/axonserver/connector/MetadataConverter.class, /org/axonframework/axonserver/connector/event/AggregateBasedAxonServerEventStorageEngine.class uses /org/axonframework/axonserver/connector/MetadataConver..."
3,4,2019,650,309,"[/org/axonframework/extension/springboot uses /org/axonframework/axonserver/connector, /org/axonframework/extension/springboot/actuator/axonserver uses /org/axonframework/axonserver/connector, /org/axonframework/extension/springboot/autoconfig uses /org/axonframework/axonserver/connector, /org/a..."